coconut-svsm/svsm

scripts/pre-commit

Without this files about to be commited are not checked, and unstaged files are checked, which is the opposite of what we want.

scripts/pre-commit: check only staged files

---

src/boot_stage2.rs
src/cpu/cpuid.rs
src/mm/pagetable.rs
src/sev/msr_protocol.rs
src/stage2.rs
src/svsm.rs

Previously the C-bit position was requested from the hypervisor by executing a SEV Information request via the GHCB MSR protocol. This allows a malicous host to feed us an incorrect value. Instead the C-bit position should be extracted from the CPUID page.

Stage2: Extract C-bit position from CPUID page

---

src/cpu/percpu.rs
src/sev/ghcb.rs
src/sev/msr_protocol.rs
src/svsm.rs
src/svsm_console.rs

Add error types for GHCB and MSR protocol operations.
These errors are mostly only to be handled from two sites, namely the firmware setup in `svsm_main()` and the `PerCpu` handlers. At the first one, we just panic as before, printing a more verbose message. At the second group, we ignore the error types for now to simplify the patches, but handling will be added in a separate PR.

Add error handling for GHCB operations

---

src/cpu/percpu.rs
src/error.rs
src/fw_meta.rs
src/lib.rs
src/mm/address_space.rs
src/mm/alloc.rs
src/mm/guestmem.rs
src/mm/pagetable.rs
src/mm/ptguards.rs
src/mm/stack.rs
src/mm/validate.rs
src/requests.rs
src/sev/ghcb.rs
src/sev/msr_protocol.rs
src/sev/utils.rs
src/sev/vmsa.rs
src/stage2.rs
src/svsm.rs
src/svsm_paging.rs

Add a new generic error type, `SvsmError`. This type can be expanded over time with additional carried information or new variants to represent different error conditions.
In general, internally each subsystem may have its own internal error type (e.g. `GhcbError`), but must return in its public interface(s) an `SvsmError`, which may contain this internal (but not private) error type with additional details (e.g. `SvsmError::Ghcb`).
For guest requests, we define a way to translate these general errors to error codes (`SvsmError` -> `SvsmReqError`) via the From trait.
Unfortunately, due to the pervasiveness of error handling and strong typing, this requires a lot of small cascading changes, so making commits self-contained was not an easy task :)

Improve error typing

---

src/cpu/idt.rs
src/cpu/percpu.rs
src/cpu/vmsa.rs
src/sev/vmsa.rs

A few fixes for some clippy warnings which should not introduce any functional changes.

Fix trivial clippy warnings

---

src/cpu/percpu.rs
src/cpu/vmsa.rs
src/fw_meta.rs
src/requests.rs
src/sev/secrets_page.rs
src/sev/utils.rs
src/svsm.rs
src/types.rs

Remove all hardcoded instances of VMPL=1 for the guest, and replace them with a new constant, `GUEST_VMPL`. Introduce as well a new value in RMPFlags so that users of the structure can easily refer to the guest VMPL.
The best home for the new constant seems to be `src/types.rs`, but this could be changed.
I have verified that a guest can be booted in VMPL 2 by simply changing the value of the constant.
Fixes #11.

Allow guest VMPL compile-time configuration

---

src/kernel_launch.rs

Previously the default representation was used which doesn't guarantee a stable layout. This is problematic because `KernelLaunchInfo` is passed from the loader to the kernel and any differences in layout would cause a crash. Using the C representation guarantees a stable layout.
Previously a crash could be provoked by setting `randomize-layout`:
```shell
RUSTFLAGS="-Z randomize-layout -Z layout-seed=2" cargo build --bin stage2
RUSTFLAGS="-Z randomize-layout -Z layout-seed=3" cargo build --bin svsm
```

SVSM: Use fixed layout for `KernelLaunchInfo`

---

src/types.rs

If an invalid guest VMPL is specified, the user will get the following error at compile time:
```
$ make
cargo build  --bin stage2
Compiling svsm v0.1.0 (/home/user/svsm)
error[E0080]: evaluation of constant value failed
--> src/types.rs:27:15
|
27 | const _: () = assert!(GUEST_VMPL > 0 && GUEST_VMPL < VMPL_MAX);
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: GUEST_VMPL > 0 && GUEST_VMPL < VMPL_MAX', src/types.rs:27:15
|
= note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0080`.
error: could not compile `svsm` due to previous error
make: *** [Makefile:30: stage1/stage2.bin] Error 101
```

svsm/types: check at compile time that guest VMPL is valid

---

src/fw_meta.rs
src/mm/address_space.rs
src/mm/mod.rs
src/mm/ptguards.rs
src/mm/virtualrange.rs
src/requests.rs
src/svsm.rs
src/svsm_paging.rs
src/types.rs
src/utils/bitmap_allocator.rs
src/utils/mod.rs

The current method of mapping a virtual memory address to a physical address involves mapping individual pages using slots, with a guard page between each virtual address. It is not possible to create a virtual memory mapping that spans multiple pages.
This new virtual address allocator allows dynamic allocation of virtual addresses that can span multiple 4K or 2M pages using a bitmap to keep track of virtual pages that are in use.
This simplifies the development of future capabilities and in particular simplifies parsing of variable size structures such as those used in the files of a firmware file system.

Replace slot-based virtual memory allocation with bitmap allocator

---

src/cpu/percpu.rs
src/mm/ptguards.rs
src/mm/virtualrange.rs
src/svsm.rs

The virtualrange allocators are global, but the address-space areas it covers are per-cpu. Change it to make the allocators per-cpu too.

Make virtualrange allocators per-cpu

---

src/cpu/percpu.rs
src/mm/virtualrange.rs

The virtual address bitfield allocator allocates a range based on the number of pages and the page size. The page size was always assumed to be 4K, so when the allocator was used with 2M pages an incorrect range was returned. This PR fixes that issue.

Add page shift size to virtual allocator to fix issue with multi-page 2M allocations.

---

Makefile
src/address.rs
src/boot_stage2.rs
src/error.rs
src/fs/api.rs
src/fs/fs.rs
src/fs/init.rs
src/fs/mod.rs
src/fs/ramfs.rs
src/kernel_launch.rs
src/lib.rs
src/mm/address_space.rs
src/mm/alloc.rs
src/mm/mod.rs
src/stage2.rs
src/string.rs
src/svsm.rs
src/utils/mod.rs
src/utils/util.rs
stage1/stage1.S

Support for a RAM filesystem and introduction of a general filesystem interface into the SVSM code-base. The filesystem is populated from a packaged archive file at boot time. The archive file is optional for now and requires a separate tool to create.

Initial implementation for a RAM filesystem

---

.github/workflows/rust.yml

Add automated actions to be executed on every push to the repository and every pull request. At the moment, every step of the build process is done except the final linking, because the runner image (ubuntu-latest) is on Ubuntu 22.04, which does not have a new enough binutils version. The actions run all the tests via make test, as well as cargo fmt to keep the code format consistent.

Add Github actions

---

.github/workflows/signed-off.yml
scripts/check-signed-off.sh

Add a new Github action to check that all commits in an incoming PR contain a `Signed-off-by` tag.

Actions: add a Signed-off-by check for incoming PRs

---

src/console.rs
src/cpu/percpu.rs
src/lib.rs
src/stage2.rs
src/string.rs
src/svsm.rs
src/utils/immut_after_init.rs

In order to achieve #15, remove nightly features:
* Remove use of `sync_unsafe_cell` feature by replacing `SyncUnsafeCell` with `UnsafeCell` + `unsafe impl Sync`.
* Remove use of `maybe_uninit_uninit_array` and `maybe_uninit_array_assume_init` features by using an array of `MaybeUninit` and raw pointers.
* Add extra tests to verify that the previous change did not break anything.
* Remove use of `const_mut_refs` feature by changing mutable references to immutable ones where possible.
- I could not find a way to keep `ImmutAfterInitRef::new_from_cell()` in, please review this change.
* Remove unused `rustc_private` feature.

Remove use of nightly features

---

scripts/check-signed-off.sh

Fix a small copy-paste error on the check-signed-off.sh script.
Fixes: 21bd15ab09dc ("Actions: add a Signed-off-by check for incoming PRs")

scripts/check-signed-off: display email on mismatch

---

src/mm/alloc.rs
src/mm/ptguards.rs

Minor cleanups for error handling in the mm subsystem. Should resolve some clippy warnings along the way.

mm: minor error handling cleanups

---

stage1/stage1.S

The size of the embedded filesystem image is rounded up on a 4 byte boundary. The end address passed to stage 2 for the filesystem uses this rounded value meaning that the code that unpacks the archive does not know the exact size of the archive. When rounding occurs, the unpacker wrongly assumes there is another file at the end and panics.
This patch retains the alignment but reports the exact archive size to stage2.

Fix rounding error in kernel filesystem binary size in stage 1 loader

---

src/cpu/gdt.rs
src/cpu/vmsa.rs
src/debug/stacktrace.rs
src/fs/fs.rs
src/fs/init.rs
src/fs/ramfs.rs
src/mm/address_space.rs
src/mm/alloc.rs

More clippy fixes. There are still a few remaining, out of which some more will be removed via #2. Once we have all of them gone, we can add clippy checks to our automated actions.

Fix even more clippy warnings

---

src/console.rs
src/cpu/cpuid.rs
src/mm/address_space.rs
src/mm/pagetable.rs
src/sev/status.rs
src/svsm.rs
src/utils/immut_after_init.rs

* Use `SyncUnsafeCell` instead of `UnsafeCell` + `unsafe impl Sync`.
* Pass Copy types by value in `ImmutAfterInitCell` methods.
* Remove a double initialization before implementing runtime detection of this condition.
* Back `ImmutAfterInitCell` by an `Option` in order to be able to detect uninitialized cells.
* Return `Result` from public API calls to handle double initialization and uninitialized access.

ImmutAfterInit: misuse runtime detection

---

src/address.rs
src/mm/memory.rs
src/mm/mod.rs
src/protocols/core.rs

Zero out a page when it is validated and before giving other VMPLs access to it. This is necessary to prevent a possible HV attack:
Attack scenario:
1. SVSM stores secrets in VMPL0 memory at GPA A
2. HV invalidates GPA A and maps the SPA to GPA B, which is in the OS range of GPAs
3. Guest OS asks SVSM to validate GPA B
4. SVSM validates page and gives OS access
5. OS can now read SVSM secrets from GPA B
The SVSM will not notice the attack until it tries to access GPA A again. Prevent it by clearing every page before giving access to other VMPLs.

Zero memory before giving access to guest

---

src/protocols/core.rs

Cleanup scattered logic about page size and alignment into a single match statement.

protocols/core: simplify page size checks during `SVSM_CORE_PVALIDATE`

---

src/address.rs
src/cpu/extable.rs
src/cpu/idt.rs
src/cpu/percpu.rs
src/debug/stacktrace.rs
src/fs/init.rs
src/fw_meta.rs
src/mm/address_space.rs
src/mm/alloc.rs
src/mm/pagetable.rs
src/mm/ptguards.rs
src/mm/stack.rs
src/mm/virtualrange.rs
src/protocols/core.rs
src/sev/ghcb.rs
src/sev/utils.rs
src/sev/vmsa.rs
src/stage2.rs
src/svsm.rs
src/svsm_paging.rs

Remove needless `Address::{offset, sub}` methods, and use the `Add` and `Sub` traits.

Address: remove offset() and sub() methods

---

src/utils/immut_after_init.rs

A recent change introduced this new warning in release builds:
warning: unused import: `core::marker::Copy`
--> src/utils/immut_after_init.rs:8:5
|
8 | use core::marker::Copy;
|     ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
Remove the line and fix it.

SVSM/utils: Fix compile warning in release builds

---

src/debug/gdbstub.rs

Address::offset() function has been removed in 39b92fb.

gdbstub: replace call to offset() with direct addition.

---

.github/workflows/rust.yml

Enable gdbstub in the test builds to catch build errors in the whole code base.

GitHub/workflows: Test-build with all features

---

INSTALL.md

Using `binutils` < 2.39, `ld` fails in this way during the build:
```bash
$ make
...
cc -o stage1/stage1 stage1/stage1.o stage1/reset.o -nostdlib -Wl,--build-id=none -Wl,-Tstage1/stage1.lds
/usr/bin/ld: section .init LMA [00000000fffffe00,00000000ffffffff] overlaps section .data LMA [00000000fffff000,00000001000dbd93]
stage1/stage1.o: in function `startup_32':
(.startup.text+0x2d): relocation truncated to fit: R_X86_64_32 against `.data'
(.startup.text+0x3d): relocation truncated to fit: R_X86_64_32 against `.data'
(.startup.text+0x44): relocation truncated to fit: R_X86_64_32 against `.data'
(.startup.text+0x4b): relocation truncated to fit: R_X86_64_32 against `.data'
(.startup.text+0x52): relocation truncated to fit: R_X86_64_32 against `.data'
collect2: error: ld returned 1 exit …
```

INSTALL.md: add binutils requirement for SVSM

---

Cargo.lock
Cargo.toml
src/fs/api.rs
src/fs/init.rs

Since we now have a [standalone crate](/coconut-svsm/packit) implementing the filesystem blob decoding, use that external crate. Also add the appropriate error conversions to keep using the question mark operator with the error type from the external crate.

fs/init: use external packit crate

---

scripts/pre-commit

Print warning if files don't contain proper header in the beginning of the file.

scripts/pre-commit: check if files contain the correct header

---

src/mm/alloc.rs

Strongly type the page type reported by `PageStorageType`, rework its usage around that and other minor cleanups

mm/alloc: strongly type page types and other cleanups

---

src/fs/filesystem.rs

Fix a new clippy warning that comes up with the latest nightly toolchain:
```
warning: this argument is a mutable reference, but not used mutably
--> src/fs/filesystem.rs:265:36
|
265 | pub fn write(fh: &FileHandle, buf: &mut [u8]) -> Result<usize, SvsmError> {
|                                    ^^^^^^^^^ help: consider changing to: `&[u8]`
|
= warning: changing this function will impact semver compatibility
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_pass_by_ref_mut
= note: `#[warn(clippy::needless_pass_by_ref_mut)]` on by default
```

fs: fix clippy warning

---

src/mm/address_space.rs

Some new features may require increasing the stack size: https://github.com/coconut-svsm/svsm/pull/69#discussion_r1282900603
To avoid problems when the gdb stub is enabled, it is best to define STACK_PAGES as a constant plus extra pages depending on the features (e.g. STACK_PAGES_GDB).
This way we have a single point to modify for the base of STACK_PAGES.
No functional changes.

address_space: add STACK_PAGES_GDB constant

---

src/fw_meta.rs

Refactor `parse_fw_meta_data()` to avoid using unsafe and raw pointers as much as possible. This mainly consists in properly typing the metadata structures and going from raw pointers to typed references or values as soon as possible. Since the firmware metadata comes from the hypervisor, it can be considered untrusted in a confidential computing model, so extra care is taken when using lengths and offsets to index into memory.
All uses of `unsafe` are documented, and all potential memory safety issues should no longer be present, making the parsing much more robust.

fw_meta: reduce raw pointer and unsafe usage

---

scripts/docker/build.sh
scripts/docker/opensuse-rust.docker

I have seem people asking about a script to build the SVSM from a container (Issue #65)as the build process depends on a recent binutils. 
This PR add scripts to build the project from a docker container. This can be useful for multiple situations e.g., build it for a CI, quick build the SVSM, or build it from a fresh environment for debugging. 
$ ./scripts/docker/build.sh
The script will not stop the container created since there is a chance it can be used again in a short term.

scripts: Build the svsm.bin from a container

---

src/mm/alloc.rs

This pr simplifies the implementation for `get_order`. This pr was inspired by this exchange on twitter: https://twitter.com/joergroedel/status/1693962505779884512.

mm: simplify get_order

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
scripts/pre-commit
src/elf/mod.rs
src/mm/pagetable.rs
src/sev/status.rs
src/sev/utils.rs

Commit a94d48d ("SVSM/sev/utils: Suppress clippy::bad_bit_mask errors") was necessary because we use an older version of bitflags. As suggested in this [1] bitflags issue, let's switch to the latest version available. In this way we can avoid to suppress clippy::bad_bit_mask.
Just minor adjustments are needed to support bitflags 2.4.0.
[1] https://github.com/bitflags/bitflags/pull/373

Update `bitflags` crate to 2.4.0

---

scripts/docker/build.sh

Using option "-r" the script uses a pre-created container. If the container was already created but it is stopped, the script is failing whit the following error:
the container name "coconut-build" is already in use by ...
Let's add "-a" option to "docker ps" to list all containers, not only the running ones.
Since we are editing this line, let's also use the CONTAINER_NAME variable for the container name.

scripts/docker: fix reuse option

---

rust-toolchain.toml

By specifying the target, rustup will automatically install the necessary toolchain if it is not present when we invoke cargo.
Suggested-by: Tom Dohrmann <erbse.13@gmx.de>

rust-toolchain.toml: set "x86_64-unknown-none" target

---

scripts/pre-commit

After the switch to stable rust the rustfmt checks triggered by the pre-commit script fail because rustfmt is invoked with parameters not available in stable rust. Remove these parameters to make the checks succeed again.

SVSM/scripts: Remove unstable rustfmt parameters from pre-commit

---

src/locking/spinlock.rs

Remove Spinlock::unlock() because it bypasses the RAII lock tracking logic of LockGuard.  This function is not used anywhere anyway.
The only way to lock the SpinLock is by acquiring a LockGuard instance via lock() or try_lock().  LockGuard automatically releases the lock when dropped.  There is no need for unlock(), it just allows messing up the holder counting.

spinlock: remove unlock()

---

src/svsm.rs

The 8 KiB of boot stack are not enough anymore after the switch to stable rust. Especially in debug builds the stack usage is higher. The maximum value I measured so far was 9608 bytes, which leads to early boot crashes. Increase the boot stack size to 16 KiB to be on the safe side.
Fixes: Github issue #90

SVSM: Increase boot-stack size

---

Makefile

The following targets were not being removed by `make clean`:
$ git check-ignore -v */*
.gitignore:3:*.elf	stage1/kernel.elf
.gitignore:8:stage1/stage1	stage1/stage1
.gitignore:2:*.bin	stage1/svsm-fs.bin
.gitignore:7:gen_meta	utils/gen_meta
.gitignore:9:print-meta	utils/print-meta

Makefile: add missing targets to clean

---

src/cpu/idt.rs
src/stage2.rs
src/svsm.rs

A couple of small fixes and cleanup. One patch also adds a new triple_fault() helper which is unused by default. But it can be used during debugging.

Fixes+cleanups

---

Makefile
src/mm/alloc.rs
src/utils/immut_after_init.rs

Our custom bare-metal allocator (`SvsmAllocator`) does not work during tests, as they run as regular userspace binaries. Thus, we must not set it as the global Rust allocator. To do this, we need a compile-time directive that lets us know we are building doctests and not the regular binary (`cfg(doctests)`), but sadly it is not properly set during test compilation (see rust-lang/rust#45599, rust-lang/rust#67295 and coconut-svsm/svsm#93).
In order to bypass this, set the compile time flag ourselves via the `RUSTFLAGS` environment variable so that tests work. Also add the new invocation to the `test` target in the Makefile.
Closes #93

tests: fix doctests and run in Makefile target

---

src/sev/ghcb.rs

If the range supplied to the the page_state_change() function is less than the maximum number of entries that the GHCB can hold, the VMGEXIT to perform the change is not issued. This has not caused an issue, yet, because when marking a range as private, the subsequent PVALIDATE will generate a #NPF and KVM will automatically change the state of the page. While likely, a hypervisor is not required to implement that behavior, which could cause the guest to spin in a #NPF loop.
This can be seen in stage 2, where the target SVSM destination was:
vaddr=0xffffff8000000000, paddr=0x8000000000, len=0x6c000
and the VMGEXIT is not issued when the page_state_change() function is invoked.
Modify the check for when to issue the VMGEXIT to include a check for reaching the end of the address range. …

sev/ghcb: Allow for page state change range smaller than max entries

---

src/fw_meta.rs
src/protocols/core.rs
src/sev/ghcb.rs
src/sev/mod.rs
src/sev/utils.rs
src/sev/vmsa.rs
src/stage2.rs
src/svsm.rs
src/svsm_paging.rs
src/types.rs

* Explicitly type the page size parameters for `pvalidate()`, `GHCB::page_state_change()` and related functions.
* Explicitly type the state parameter for `pvalidate()`.
This way, the following:
```rust
pvalidate(vaddr, false, true)?;
```
Turns into:
```rust
pvalidate(vaddr, PageSize::Regular, PvalidateOp::Valid)?;
```
And this:
```rust
this_cpu_mut()
.ghcb()
.page_state_change(pstart, pend, false, PageStateChangeOp::PscPrivate)
```
turns into:
```rust
this_cpu_mut()
.ghcb()
.page_state_change(
pstart,
pend,
PageSize::Regular,
PageStateChangeOp::PscPrivate,
)
```

types: explicitly type page size parameters

---

src/locking/rwlock.rs

Fix an undefined behavior that could be triggered when acquiring a read guard on a RWLock. This happened because a ReadLockGuard would keep a mutable reference to the underlying shared data. Since one might acquire multiple ReadLockGuards to the same data, this would lead to undefined behavior under Rust's borrowing rules.
This was found by @Freax13 while running @Zildj1an's tests in #105 under the [Miri](/rust-lang/miri) interpreter.
Fixes: b29acca1 ("SVSM/locking: Add RWLock implementation")
Reported-by: Tom Dohrmann <erbse.13@gmx.de>

locking/rwlock: fix undefined behavior via `RWLock::lock_read()`

---

.github/workflows/rust.yml
src/fs/filesystem.rs
src/fs/ramfs.rs
src/mm/alloc.rs

Running `cargo clippy --tests --target=x86_64-unknown-linux-gnu --all-features` highlighted several things that we can improve in our tests code.
Only tests are affected, so no change to code behavior.
We need to add a second call to clippy for tests in the CI because we need to use a different target (i.e. x86_64-unknown-linux-gnu) to avoid build failure.
I squashed all the tests changes in a single commit since they are tests, but if you prefer I can split them in several commits.

run clippy on tests on the CI and fix several warnings

---

src/mm/alloc.rs

Fix the undefined behavior detailed in #107 by acquiring a lock to the corresponding `Slab` before freeing an allocation from it. Before, this could lead to undefined behavior, as freeing an address would access the Slab mutably, regardless of any concurrent users.
The appropriate `Slab` can be found by using the `layout` parameter to `SvsmAllocator::dealloc()`.
The PR also includes small refactors and cleanups to make the change simpler.
This does not completely solve #107 because by avoiding this UB, further UB warnings are revealed.

mm/alloc: acquire `Slab` spinlock when freeing a pointer

---

Cargo.toml
Makefile
src/mm/alloc.rs

Our custom bare-metal allocator (`SvsmAllocator`) cannot be used in regular userspace binaries so needs to be disabled for unit and doc testing. The previous fix for documentation tests used the `doctest` cfg to conditionally use the allocator, passing the configuration option via RUSTFLAGS. Unfortunately, this caused compilation issues with dependencies that make use of #[cfg(doctest)] such as memoffset which is used by intrusive-collections.
Instead, this change makes use of the fact that the tests run on an OS platform whereas the SVSM is built for a target OS of 'none'. The custom allocator is enabled only when `target_os` = "none". This means the specific docs test invocation can be removed from the test Makefile target as the doc tests will be run alongside the unit tests.

test:  Use target OS to determine use of bare-metal allocator

---

INSTALL.md

The branches with the Linux kernel support for SVSM (guest and host side) have been updated to use the latest upstream patch-sets. Same for QEMU, which was updated to version 8.0.0.
Update the documentation to point to the updated branches.

INSTALL.md: Document new Linux kernel and QEMU branches

---

src/mm/memory.rs
src/mm/pagetable.rs

Starting with v9 of the SEV-SNP KVM host patches, the guest physical address of VMSAs is fixed and longer depends on the CPU's limits.
The recommended branch at https://github.com/coconut-svsm/linux/tree/svsm is using v9 (or maybe even newer?).

mm: hard-code VMSA address

---

src/acpi/tables.rs
src/elf/mod.rs

Document ELF and ACPI tables code and structures.
This is related to issue #74 Document COCONUT-SVSM.

docs: Document ELF and ACPI tables

---

src/mm/stack.rs
src/utils/mod.rs
src/utils/util.rs

Remove the use the `ffs()` function in favor of `u64::trailing_zeros()`. Both functions work identically except when the value is zero, where `ffs()` returns `u64::MAX` and `u64::trailing_zeros()` simply returns `u64::BITS` (64), which is fine for our use case.
The function has no other users, so it can be removed. This also removes an unsafe block, and allows running Miri on the upcoming stack tests (#126), since Miri does not work on inline assembly. Additionally, the new code runs twice as fast in my own (naive) benchmarks.

mm/stack: remove use of `ffs()`

---

src/mm/alloc.rs

Bounds check the order parameter to `MemoryRegion::refill_page_list()` before indexing, as an invalid order could cause an out of bounds access, resulting in a panic. The previous bounds check was too late, and also had an off-by-one bug.
This function is reachable from other modules via `allocate_pages()`, which naively forwards the order parameter.
Fixes: bee9fe779bf0 ("SVSM: Implement higher-order allocations")

mm/alloc: bounds-check page order before indexing

---

src/fs/filesystem.rs
src/fs/ramfs.rs
src/mm/alloc.rs

Replace `setup_test_root_mem()` and `destroy_test_root_mem()` by a new guard-like struct that, when acquired, grabs a global lock and initializes the test memory, and when dropped it destroys the memory before releasing the lock.
This simplifies some tests by removing the need to manually destroy the global memory. Moreover, guards on `ROOT_MEM` do not need to be dropped manually either, since they are always acquired after the memory lock, and Rust drops objects in reverse order of acquisition.

tests/mm: use RAII guard to drop test root memory

---

src/mm/vm/mapping/rawalloc.rs

Fix a broken link in the generated documentation for `RawAllocMapping`, which will cause a CI break with the upcoming changes in #124.

docs/mm: fix broken link in `RawAllocMapping` description

---

src/acpi/tables.rs
src/fw_cfg.rs

Limit hypervisor-controlled allocation sizes to prevent potential OOM issues. This is done in places where big allocation sizes (for example a huge number of firmware files or very big ACPI tables) would make no sense in a reasonable implementation.
This will also be useful for fuzzing performance once #113 is merged.

acpi/tables, fwcfg: limit hypervisor-controlled allocation sizes

---

src/mm/stack.rs

Add basic unit tests for the stack. This is a start to adding unit tests to all memory components.

mm: stack: Add unit tests

---

src/types.rs

Move the guest OS to VMPL-2, keeping VMPL-1 for future usage to the SVSM and VMPL-3 for future usage to the OS.

SVSM: Execute Guest OS at VMPL-2

---

src/mm/pagetable.rs

The `page` argument was a mutable reference, but not used mutably, so let's make it immutable.

SVSM/mm/pagetable: avoid mutable reference in RawPageTablePart::free*()

---

.github/workflows/rust.yml
.gitignore
Cargo.lock
Cargo.toml
INSTALL.md
Makefile
build.rs
scripts/test-in-svsm.sh
src/fs/filesystem.rs
src/fs/ramfs.rs
src/lib.rs
src/mm/address_space.rs
src/mm/alloc.rs
src/svsm.rs
src/testing.rs
test/Cargo.toml
test/src/lib.rs
utils/cbit.c

This PR makes it possible to run tests inside the SVSM. Simply setting the `TEST` environment variable before running `make` will produce an SVSM build that runs tests instead of running the guest.
This is implemented using the nightly `custom_test_frameworks` feature to specify our own tests runner. This nightly feature is only required when building tests for running inside the SVSM, non-test builds and normal test execution can continue to use a stable toolchain. The `#[test]` macro expects a crate named `test` to exist, so a small, no_std compatible subset of the `test` crate has been copied.
Some  tests currently fail when run inside the SVSM (AFAICT mostly for benign reasons related to setup of the allocator and file system). Those tests are currently disabled using the `ignore` …

run tests inside SVSM

---

scripts/check-signed-off.sh

Check if any of the `Signed-off-by` commit trailers match the commit author instead of expecting a single trailer.

scripts/check-signed-off: allow more than one `Signed-off-by` trailer

---

src/cpu/percpu.rs
src/mm/address_space.rs
src/mm/vm/mod.rs
src/mm/vm/range.rs
src/task/tasks.rs

Now that virtual memory ranges and page table entries can be managed using the new `VMR` and associated structs, update the Task structure implementation to manage the task pagetable using these new capabilities.
The task structure now includes a `VMR` instance that defines the virtual address range for the task. The kernel stack for the task is created using `VMKernelStack` and added to the task VMR. This is applied to the task pagetable during creation.
`PerCpu` already includes a per cpu VMR. This needs to be applied to the task when it is context switched onto the CPU. Currently this is done directly by copying the PerCpu level 3 index. This patch adss the function `populate_page_table()` to PerCpu which applies the PerCpu VMR to the pagetable instead.

task, percpu: Use VMR to manage the task pagetable and VMKernelStack to allocate the task kernel stack

---

src/acpi/tables.rs
src/console.rs
src/cpu/cpuid.rs
src/cpu/gdt.rs
src/cpu/idt.rs
src/cpu/percpu.rs
src/cpu/registers.rs
src/cpu/tss.rs
src/debug/stacktrace.rs
src/elf/mod.rs
src/fw_cfg.rs
src/io.rs
src/kernel_launch.rs
src/lib.rs
src/mm/alloc.rs
src/mm/guestmem.rs
src/mm/pagetable.rs
src/mm/ptguards.rs
src/mm/vm/mapping/phys_mem.rs
src/mm/vm/mapping/reserved.rs
src/protocols/mod.rs
src/serial.rs
src/sev/ghcb.rs
src/sev/msr_protocol.rs
src/sev/secrets_page.rs
src/sev/vmsa.rs
src/svsm_console.rs
src/task/tasks.rs
src/utils/bitmap_allocator.rs
src/utils/immut_after_init.rs

* Add missing `Copy` derives, plus a lint to prevent their absence in the future.
* Add missing `Debug` derives, plus a lint to prevent their absence in the future.

svsm: add missing `Copy` and `Debug` derives

---

src/cpu/percpu.rs
src/elf/mod.rs
src/mm/alloc.rs
src/svsm.rs

Fix warnings that appear on the nightly version of clippy. These simply improve code clarity, there is no functional change.

Fix nightly clippy warnings

---

fuzz/Cargo.toml
fuzz/fuzz_targets/alloc.rs
fuzz/fuzz_targets/page_alloc.rs
src/mm/alloc.rs

Add two fuzzing harnesses. One explicitly targets page allocation, while the other one targets the higher level `SvsmAllocator` API.

fuzzing: add allocator harnesses

---

src/cpu/percpu.rs
src/mm/pagetable.rs
src/mm/ptguards.rs
src/mm/stack.rs
src/svsm_paging.rs

Minor code quality improvements for the pagetable code.

mm/pgtable: minor cleanups

---

src/cpu/idt.rs
src/cpu/percpu.rs
src/fs/api.rs
src/fs/filesystem.rs
src/fs/ramfs.rs
src/mm/vm/mapping/api.rs
src/mm/vm/mapping/file_mapping.rs
src/mm/vm/mapping/kernel_stack.rs
src/mm/vm/mapping/mod.rs
src/mm/vm/mapping/phys_mem.rs
src/mm/vm/mapping/rawalloc.rs
src/mm/vm/mapping/reserved.rs
src/mm/vm/mapping/vmalloc.rs
src/mm/vm/mod.rs
src/mm/vm/range.rs
src/task/tasks.rs

In order to be able to provide the ability to load and map ELF files into a task virtual memory space, we need the ability to take RamFS files and create virtual memory ranges to map the file physical pages to virtual memory addresses.
This PR uses the new `VirtualRange` trait and `VMR` ranges to implement a range that takes ownership of a file handle and allows a view of the file to be created as a virtual memory range and added to any `VMR` such as within the current task or the PerCpu range.
The goal of the implementation is to keep the file system contents as immutable, providing read-only access to the backing pages and copy-on-write access for writable access.
Multiple `VMFileMapping` ranges can be created over a single file by opening multiple file handles on the same file.

fs: Add VMFileMapping to map ramfs file contents to virtual memory

---

src/mm/vm/mapping/rawalloc.rs

Fix a broken link in the generated documentation for `RawAllocMapping`, which will cause a CI break with the upcoming changes in #124.

docs/mm: fix broken link in `RawAllocMapping` field

---

src/locking/rwlock.rs
src/locking/spinlock.rs

Document locking support. This is related to issue #74 Document COCONUT-SVSM.

docs: Document SpinLock and RWLock

---

src/address.rs
src/debug/stacktrace.rs
src/fw_cfg.rs
src/fw_meta.rs
src/kernel_launch.rs
src/mm/memory.rs
src/mm/pagetable.rs
src/mm/ptguards.rs
src/mm/stack.rs
src/mm/validate.rs
src/stage2.rs
src/svsm.rs
src/utils/memory_region.rs
src/utils/mod.rs

As described in #114, the SVSM `PVALIDATE`s and uses hypervisor-provided memory regions without any checks, which could lead to the SVSM kernel doubly validating its own memory.
In order to fix this, introduce a new type, `MemoryRegion`, to serve as a common type to perform these kinds of checks. While we are at it, use this new type everywhere possible instead of having per-module types with essentially the same functionality.
While we are at it, cleanup code around the use of memory regions.
Fixes #114.

fw_meta: do not trust firmware metadata memory regions

---

src/cpu/idt.rs
src/cpu/percpu.rs
src/cpu/smp.rs
src/debug/gdbstub.rs
src/error.rs
src/locking/rwlock.rs
src/mm/address_space.rs
src/svsm.rs
src/task/mod.rs
src/task/schedule.rs
src/task/tasks.rs

This PR builds on the merged task switching PR https://github.com/coconut-svsm/svsm/pull/61 and also the draft scheduler PR https://github.com/coconut-svsm/svsm/pull/50 to add scheduling support to coconut-SVSM.
Two different task lists have been implemented in task/schedule:
* Firstly all newly created tasks are added to a simple doubly-linked list where they remain until the task is terminated and subsequently closed. An instance of the tasklist is provided globally and can be used to determine the status of every task.
* Secondly, an RB tree based list is implemented that sorts tasks based on their calculated execution time. The shortest running task and hence the highest priority task for scheduling is leftmost on the tree. Each CPU creates an instance of the RB tree named `runqueue` …

task/schedule: Implement scheduler and per-cpu runqueues

---

src/mm/alloc.rs
src/mm/mod.rs

Simplify certain code paths, mostly related to heap page management, and simplify syntax where possible.

mm/alloc: multiple simplifications and cleanups

---

.github/workflows/rust.yml
Makefile
README.md

Add Makefile target to generate cargo documentation and update README accordingly.

docs: Add Makefile generation target and CI testing 

---

src/cpu/cpuid.rs
src/cpu/extable.rs
src/cpu/idt/common.rs
src/cpu/idt/mod.rs
src/cpu/idt/stage2.rs
src/cpu/idt/svsm.rs
src/cpu/insn.rs
src/cpu/mod.rs
src/cpu/vc.rs
src/cpu/vmsa.rs
src/debug/gdbstub.rs
src/debug/stacktrace.rs
src/error.rs
src/stage2.rs
src/svsm.rs

This is a draft for the implementation of #14, which is implementing a #VC handler to handle NAE events.
NAE events have to be handled early, so we also set and load the IDT in stage 2.
At this point, interrupt handling in stage 2 doesn't work. I mostly moved and debug code to try to call the VC handler from a stage 2 `cpuid`, which fails. The IDT setup in this PR still handles interrupts in the SVSM kernel, but not in stage 2. My guess goes that IDT entries should be different because stage2 is a different binary (with different GDT entries?), but I'm still debugging. That's where my lack of system programming background hits.

Add #VC handler

---

src/cpu/idt/stage2.rs
src/cpu/vc.rs

The #VC handler added in stage 2 breaks the gdb-enabled builds due to a too big stage 2 binary.
Breakpoints handling in stage 2 is breaking, and useless so we can drop the handler function calls so that gdbstub code is not included in stage 2 binary.

cpu/vc,idt: drop debug support in stage2

---

src/mm/validate.rs

* Remove useless `pub` on `ValidBitmap` methods.
* Fix: if the number of pages in the bitmap was not a multiple of 64, the remainder would not be copied over to the new bitmap during migration, which could lead to tracking validated pages as invalid.
* Use an `usize` to index into the bitmap, as offsets are always positive.
* Fully clear the bitmap after initialization.

mm/validate: fully migrate and clear bitmap & other cleanups

---

src/cpu/vc.rs
src/debug/gdbstub.rs

handle_db_exception was only used in the SVSM #VC handler. This function was calling handle_debug_exception under the hood.
We can remove handle_db_exception and integreate its logic into handle_debug_exception so that it remains only 1 debug exception handling function.

debug: remove handle_db_exception

---

src/cpu/idt/stage2.rs

When building the fuzzing harnesses, rustc would complain that `push_regs` was defined twice. Fix this by renaming `push_regs` in stage 2 to `push_regs_stage2`.
```
error: symbol 'push_regs' is already defined
|
note: instantiated into assembly here
--> <inline asm>:105:5
|
105 |     push_regs:
|     ^
error: could not compile `svsm` (lib) due to previous error
```
This would happen because both symbols were declared globally in both binaries (svsm and stage2), and would both get included by the fuzzing harnesses, which depend on the whole svsm crate.

stage2: rename `push_regs` to `push_regs_stage2`

---

src/utils/util.rs

Miri emits an error for `test_zero_mem_region()` (trace below) because `start` is a mutable reference only to the first element of the array, but we end up writing to the whole buffer, for which we do not have write access.
Take a mutable pointer to the whole buffer instead.
<details>
<summary>Miri trace</summary>
```
Miri error:
test utils::util::tests::test_zero_mem_region ... error: Undefined Behavior: attempting a write access using <wildcard> at alloc65762[0x1], but no exposed tags have suitable permission in the borrow stack for this location
--> src/utils/util.rs:47:14
|
47 |     unsafe { start.as_mut_ptr::<u8>().write_bytes(0, size) }
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|              |
|              attempting a write access using <wildcard> at …
```

utils/tests: fix undefined behavior in `test_zero_mem_region()`

---

Cargo.lock
Cargo.toml
src/greq/driver.rs
src/greq/msg.rs
src/greq/pld_report.rs

* Fix UB in `SnpGuestRequestMsgHdr::get_aad_slice()`
* Fix reachable assertions in `SnpGuestRequestExtData::boxed_new()` and `SnpGuestRequestMsg::boxed_new()`.
* Add tests for layout-sensitive structs.
* Refactor assertions that can be evaluated at compile time
* Other syntax & readability cleanups

greq: bugfixes, layout correctness tests and other cleanups

---

fuzz/Cargo.toml
fuzz/fuzz_targets/insn.rs

The x86 instructions decoder is very convenient attack surface.
For the moment, the decoder code is only reachable from CPL-0, but it will be reachable from less privileged code when CPL-3 will be supported. The decoder is currently reachable from a #VC exception.

fuzz: add x86 instructions decoder harness

---

src/error.rs
src/mm/alloc.rs

Add a new `AllocError` enum that will be wrapped in `SvsmError::Alloc`, so that memory allocation errors are more specific than the generic `SvsmError::Mem`.

mm/alloc: add allocator-specific errors

---

src/cpu/vc.rs

The VC exception handler forwards trap exceptions to the GDB stub. However, the wrong error code was being used to detect the trap exception, preventing the GDB stub from working. This commit fixes that.

cpu/vc: Fix VC exception handler index for trap exception

---

src/mm/address_space.rs
src/mm/guestmem.rs
src/mm/memory.rs

Add unit tests to evaluate offline correct behavior of memory components: kernel mappings (address_space.rs), read and write operations (guestmem.rs) and valid physical address checking (memory.rs).

mm: Add unit tests for kernel mapping, guestmem ops, address checks

---

Cargo.lock
Cargo.toml
igvm_params/Cargo.toml
igvm_params/src/lib.rs
src/config.rs
src/igvm_params.rs
src/kernel_launch.rs
src/lib.rs
src/stage2.rs
src/svsm.rs
src/svsm_paging.rs
stage1/stage1.S

If the SVSM is being launched from an IGVM file, it will supply parameters using IGVM directives.  The SVSM must consume those parameters when present instead of obtaining them from QEMU-specific interfaces.
The IGVM file generation tool will be submitted in a future pull request.

Obtain configuration parameters from IGVM when present

---

igvm_params/src/lib.rs
src/config.rs
src/igvm_params.rs
src/kernel_launch.rs
src/stage2.rs
src/svsm.rs

Permit the IGVM configuration to specify a debug output port other than COM1.  This is specified at the time the IGVM file is built and is not selectable by the host loader.

Acquire the choice of debug serial port from the IGVM parameter block

---

src/mm/vm/mapping/api.rs
src/mm/vm/mapping/reserved.rs
src/mm/vm/range.rs

Add a flag to the virtual mapping object indicating whether the mapping is backed by any data.  This permits the VMM creation code to avoid thousands of worthless calls to "get data" on large reserved ranges which supply no data to map.

Optimize VMM creation of reserved ranges

---

src/mm/alloc.rs

When the heap free list is first constructed, the list of pages is divided into a region of free page groups, one of which is aligned to a multiple of the size of the maximum free order, and the others are unaligned head/tail regions.  The aligned group is freed directly to the maximum order bucket, which avoids the need to do neighbor searching in order to construct the large buckets.  No similar optimization is performed on intermediate sizes of the unaligned head/tail regions because they are too small to worry about.

Optimize creation of the memory heap

---

igvm_params/src/lib.rs
src/config.rs
src/fw_cfg.rs
src/igvm_params.rs
src/svsm.rs

This changes the IGVM parameter block to replace the flag that indicates whether to boot OVMF with two parameters that define the GPA range of the OVMF region. 
The same constraints on OVMF location are currently still true - the OVMF pages must be aligned up to the 4GB boundary therefore the IGVM builder must ensure this alignment for OVMF to be booted correctly.

IGVM: Add support for launching OVMF firmware when using an IGVM file for guest configuration

---

FUZZING.md

Remove link in fuzzing documentation that leads to 404 (page not found).

fuzzing: remove broken link (404 page not found)

---

Cargo.lock
Cargo.toml
igvm_params/src/lib.rs
src/igvm_params.rs
src/svsm.rs

The IGVM format was just extended to define "environment information", which permits the loader to declare some information about the environment, such as whether or not the hosting environment pre-assigns all memory to the guest or whether the memory begins in the unassigned state.  This PR modifies the IGVM parameter handling to conform to the new IGVM parameter.

Switch to the latest IGVM definition of "environment info"

---

FUZZING.md

A broken link was removed but not replaced with a working one.
Fixes: 51db3292 ("fuzzing: remove broken link (404 page not found)")

fuzzing: restore documentation link to cargo-fuzz

---

.gitignore
Makefile
igvmbld/igvm_defs.h
igvmbld/igvmbld.c
igvmbld/sev-snp.h

This C-based IGVM file builder can create simple IGVM files for use either under QEMU or Hyper-V.  It was written in C in order to create a first implementation quickly, but will be replaced with a Rust version in the near future.  Until then, the C version should be maintained in sync with any IGVM parameter consumption in the SVSM.

Add C-based IGVM file builder

---

src/mm/vm/mapping/api.rs
src/mm/vm/mapping/file_mapping.rs
src/mm/vm/range.rs

Minor cleanup and readability changes.

mm/vm: minor cleanups

---

fuzz/Cargo.toml
fuzz/fuzz_targets/bitmap_allocator.rs
src/utils/bitmap_allocator.rs

Added a fuzz harness for bitmap_allocator.  This might not be interesting from a security perspective, but more  from stress testing perspective.

fuzz: add bitmap_allocator harness.

---

src/requests.rs
src/svsm.rs

Permit the guest to execute without having a calling area configured.  In the future, when running in a paravisor configuration, there will be no calling area, so execution must not be blocked due to the absence of a calling area.  When running in a pure SVSM configuration, lack of a calling area renders the SVSM useless but does not introduce any functional issue.

Permit guest execution without a calling area

---

igvm_params/src/lib.rs
src/igvm_params.rs

The other fields in IgvmParams that describe sizes are in bytes rather than pages whereas fw_size is in pages. This commit updates fw_size to describe the firmware size in bytes to be consistent.

igvm_params: Modify fw_size parameter to be in bytes rather than pages

---

igvmbld/igvmbld.c

The initial VMSA populates the segment registers but does not set values for the selectors. The current IGVM loader in QEMU requires the selectors to be set correctly to start the guest. This patch sets the selectors to the values expected by the SVSM.

Add segment selectors to initial VMSA in the IGVM builder

---

src/requests.rs
src/sev/ghcb.rs
src/svsm.rs

Ensure that every entry to the guest VMPL occurs from the same point in the execution loop.  This will become important in the future when REFLECT_VC is enabled, and will be critical on non-SNP platforms that do not use simple GHCB calls for guest entry.

Enter the guest VMSA from a consistent place

---

igvmbld/igvmbld.c
src/config.rs
src/svsm.rs
src/svsm_paging.rs

- Move the kernel ELF/fileystem so they do not collide with low memory ROMs
- Invalidate the kernel ELF/filesystem memory so it can be reused by OVMF

Fix issues with IGVM boot

---

bootlib/src/igvm_params.rs
igvmbld/igvmbld.c
src/config.rs
src/fw_meta.rs
src/igvm_params.rs
src/svsm.rs

This change permits the IGVM file to specify firmware metadata that would normally be read out of QEMU firmware metadata.  This permits the IGVM file to specify metadata without external reference, and permits SVSM configuration of firmware metadata on platforms other than QEMU.

Supply firmware metadata information via the IGVM parameter block

---

Makefile
bootlib/src/igvm_params.rs
igvmbld/igvm_defs.h
igvmbld/igvmbld.c
igvmbld/ovmfmeta.c
igvmbld/ovmfmeta.h
src/config.rs
src/igvm_params.rs
src/svsm.rs

This PR adds support for embedding firmware, particularly OVMF into an IGVM file using the IGVM builder. 
The Makefile has been updated to allow the OVMF file to be specified by the `FW_FILE` environment variable. This needs to be set to the `OVMF.fd` file (and not the separate `OVMF_CODE.fd` and `OVMF_VARS.fd` files). When provided, the firmware binary is parsed by the IGVM builder during the build to extract metadata which is then populated into the IGVM parameter block, passed to SVSM.
By providing the metadata in the IGVM parameter block, SVSM does not need to parse the OVMF metadata when using an IGVM file. The SVSM has been updated to reflect this by removing the `fw_metadata` IGVM parameter that specified the OVMF metadata page. In the future, if IGVM is solely used to configure …

IGVM: Embed firmware in IGVM file and parse OVMF metadata into IGVM parameter block

---

src/svsm.rs

This change enables booting Coconut without any guest firmware, which is useful for testing the boot process.

Suppress transition to guest VMPL when no firmware is specified

---

src/sev/mod.rs
src/sev/msr_protocol.rs
src/svsm.rs

This is used to verify that the hypervisor implements all of the GHCB features required (since not all of them are guaranteed by virtue of supporting version 2 of the GHCB protocol) and captures any optional features that may influence SVSM behavior.

Query hypervisor GHCB features during SVSM startup

---

igvmbld/igvmbld.c

When firmware runs in low memory, the entire stage 2 region (the low 640 KB) is validated as part of the IGVM image.  The IGVM file should not request re-validation of the range between the top of the stage 2 image and the 640 KB boundary.

Prevent duplicate page validation with low-memory firmware.

---

igvmbld/igvmbld.c
igvmbld/igvmbld.h
igvmbld/igvmcopy.c

In order to help validate and debug issues around allocation of guest physical address ranges, and to ensure it matches the expectations of coconut SVSM, it is useful to see what is generated by the IGVM file builder.
This commit extends the verbose output from the tool to show the purpose and the range for each block of guest physical memory defined by the generated IGVM file as well as giving a detailed summary of the contents of the IGVM parameter block.

igvmbld: Extend verbose mode to show guest memory and igvm params

---

bootlib/src/kernel_launch.rs
igvmbld/igvmbld.c
igvmbld/igvmbld.h
igvmbld/igvmcopy.c
src/stage2.rs
src/svsm_paging.rs

When booting using an IGVM configuration, the current IGVM builder places some of the prevalidated pages outside the first 640K of low memory. These need to be invalidated prior to booting the firmware. 
This PR moves some of the regions in the IGVM builder and detects and invalidates the relevant sections in the SVSM when using IGVM.
Note that this PR is based on a branch which already includes the commit under separate review #206. Please ignore commit d6b606cfb1e283d3973b357f450a3a6a30fa4a41 when reviewing this PR.

Ensure all boot memory is invalidated when QEMU guest is configured with IGVM

---

src/sev/utils.rs

The previous PVALIDATE code issued "xor eax, eax" immediately after the call to PVALIDATE, but XOR will set CF=0.  This hides any CF-based error returned by the PVALIDATE instruction.
This change exposes validation bugs in the current code, and should not merge until at least #207 and #208 have merged.

Fix PVALIDATE

---

src/mm/mod.rs
src/mm/page_visibility.rs

This PR implements helper functions that handle all aspects of changing the visibility of an SVSM-owned page, including performing PVALIDATE, tracking valid page status, requesting the page state change with the hypervisor, and changing the C-bit in the page tables.

Add utility function to change visibility of SVSM pages

---

src/cpu/percpu.rs
src/protocols/core.rs
src/svsm.rs

In order to preserve the Rust guarantees of mutually exclusive mutable and immutable references, it must never be possible for a PerCpu object to be accessible across threads, even to access fields that are designed to be thread-safe.  This change moves globally shared per-CPU fields into a separate structure that supports only immutable references, and fields contained within are synchronized using appropriate locking primitives that permit safe interior mutability.

Move shared CPU state into a separate structure

---

igvmbld/igvmbld.c

The change made in commit 571db22fbaba413a9299b14aafa294e251ed646c that reduces the memory range for stage2 was lost in a subsequent commit causing two memory ranges to overlap in the IGVM file. This is subsequently rejected by the QEMU builder causing the guest to fail to startup.
This commit fixes the merge error.

igvmbld: Fix merge error that caused overlapping memory regions

---

scripts/check-signed-off.sh

Check that all new commits have a commit body besides the summary line and git trailers.
Unfortunately git does not have a direct option to show the body (i.e. everything after the summary line) without the trailers, so we have to filter them out manually.

scripts/check-signed-off: check that commits do not have an empty body

---

bootlib/src/igvm_params.rs
igvmbld/igvmbld.c
igvmbld/igvmbld.h
igvmbld/ovmfmeta.c
src/fw_meta.rs
src/igvm_params.rs

The data from the SEV_INFO metadata field is never consumed anywhere, so
there is no reason to collect any data from it.

Remove references to SEV_INFO OVMF metadata since it is never used

---

igvmbld/igvmbld.c

The stage2 stack page memory is allocated with a call to construct_mem_data_object(). This function zeros any padding outside of the requested data size but does not zero the memory where the data resides.
The stage2 stack is allocated as a full page, meaning the stack is not initialised to zero. This results in uninitialised data being present below the populated stack frame and in the _reserved part of the stack.
This commit zeroes the entire stack page to ensure it is initialised.

igvmbld: Zero stage2 stack page before populating it

---

Makefile

Closes Issue#72
We've tested the addition of the -no-pie flag here and found it to both close Issue#72 and successfully boot, i.e., the build is correct.

Fix relocation error when linking stage1

---

src/cpu/insn.rs
src/cpu/vc.rs

- Introduce InsnBuffer for similar Instructions fields.
-  Add unit tests for x86 instructions deocding
- Add documentation for svsm::cpu::insn

Introduce InsnBuffer and other improvements

---

src/debug/stacktrace.rs

There were a couple of errors when building with `enable-stacktrace` disabled (e.g. `cargo b --no-default-features`):
* `StackUnwinder` did not have a `Debug` derive, which caused a warning due to `deny(missing_debug_implementations)`.
* `print_stack()` had different arguments depending on the feature, but it was called assuming one of those two versions from feature-independent code.
* Imports were causing warnings due to them not being used when the feature was disabled.
* Some structs were not used at all when the feature was disabled, but there were no warnings since they were (unnecessarily) declared as `pub`.

debug/stracktrace: fix build when `enable-stacktrace` is disabled

---

src/cpu/gdt.rs
src/cpu/idt/common.rs
src/cpu/idt/mod.rs
src/cpu/idt/stage2.rs
src/cpu/idt/svsm.rs
src/cpu/mod.rs
src/cpu/percpu.rs
src/cpu/tss.rs
src/cpu/vmsa.rs
src/greq/driver.rs
src/mm/alloc.rs
src/sev/mod.rs
src/sev/secrets_page.rs
src/stage2.rs
src/svsm.rs

Add decent implementations for the GDT, IDT and SecretsPage which require proper locking to make modifications.
This fixes a couple of warnings triggered by the latest Rust nightly compiler.

Get rid of some mutable global statics

---

src/fs/filesystem.rs

Fix the following clippy warning that comes up with the nightly toolchain:
```
warning: this bound is already specified as the supertrait of `DoubleEndedIterator`
--> src/fs/filesystem.rs:260:47
|
260 | fn split_path_allow_empty(path: &str) -> impl Iterator<Item = &str> + DoubleEndedIterator {
|                                               ^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#implied_bounds_in_impls
= note: `#[warn(clippy::implied_bounds_in_impls)]` on by default
help: try removing this bound
|
260 - fn split_path_allow_empty(path: &str) -> impl Iterator<Item = &str> + DoubleEndedIterator {
260 + fn split_path_allow_empty(path: &str) -> impl DoubleEndedIterator<Item = &str> {
```

fs/filesystem: make trait bounds more concise

---

fuzz/Cargo.lock
src/fw_meta.rs

If the CPUID page is absent simply log it and return an error instead of panicking. This was causing problems with the `fw_meta` fuzzer.
While we are at it, update the Cargo.lock file for the fuzz subdirectory.

fw_meta: do not panic on CPUID page absence

---

src/cpu/percpu.rs
src/requests.rs
src/svsm.rs

Tie guest VMSA reference lifetime to the VMSA reference lock scope.
Remove requirement for mutability on PerCpu reference to obtain the guest VMSA, since the guest VMSA reference is protected by a spin lock and does not require static borrow checking.

Fix guest VMSA borrowing lifetimes and mutability requirements

---

src/cpu/percpu.rs
src/sev/ghcb.rs

In `PerCpu::setup_ghcb()`, a pointer to allocated but uninitialized memory was being cast to a pointer to a GHCB struct. This pointer in turn was used to call `GHCB::init()`, which takes `&mut self`, which creates a reference to uninitialized memory. The GHCB struct consists simply of scalar values, so it has no invalid representations, but this is unnecessarily unsafe.
To avoid an unsafe block and potential future issues, allocate the page zeroed, and make `GHCB::init()` take a `VirtAddr` which can properly be initialized.
While we are at it, do not store the pointer in the `PerCpu` struct until it has been properly initialized.

cpu/percpu: do not create a reference to uninitialized memory

---

src/svsm.rs

Document some of the unsafe blocks around the SVSM main function. This includes an extra alignment check that was not being made.

svsm/main: add some safety comments

---

src/mm/pagetable.rs
src/mm/ptguards.rs
src/mm/virtualrange.rs
src/sev/utils.rs
src/stage2.rs
src/svsm_paging.rs

The type is fitting for more uses in a couple of subsystems, so use it instead of address pairs in several places. This homogenizes several interfaces and makes code simpler to follow, as a single variable is passed around instead of two.

Add more uses of `MemoryRegion`

---

Cargo.toml
src/cpu/idt/common.rs
src/cpu/percpu.rs
src/debug/stacktrace.rs
src/mm/stack.rs
src/mm/vm/mapping/kernel_stack.rs
src/task/tasks.rs

The stack trace code is not yet aware of task stacks. This causes no stack-traces to be collected or printed at all at the moment, when the stack trace is collected from task context.
This PR fixes that and also the assumption about when the end of the stack is reached.

Stack trace fixes

---

src/cpu/percpu.rs
src/cpu/smp.rs
src/debug/gdbstub.rs
src/requests.rs
src/svsm.rs
src/task/mod.rs
src/task/schedule.rs
src/task/tasks.rs
src/task/waiting.rs

Here are changes to the Task and Scheduler implemenation of COCONUT-SVSM. The highlights are:
* Move from a time-slice based to a simpler round-robin scheduler
* Remove affinity and allocation code - relying fully on WaitQueues to move tasks between CPUs
* Merge TaskNode and Task structs into one
* Rework locking for struct Task
Building on the Task/Scheduler changes this PR also introduces a simple WaitQueue and a BLOCKING task state, which allows to put tasks to sleep and wake them up again.
Finally the last patch in the PR uses all of that to move core protocol request processing into a separate kernel task.

Rework Task and Scheduler Code

---

Makefile

When building the igvmbuilder binary, respect `CARGO_ARGS`, which potentially includes among other things the `--release` flag. This was causing an error when building in release mode, as the resulting binary was being placed in the debug build path, but the Makefile was expecting it to be placed in the release path:
```
/bin/sh: line 1: target/x86_64-unknown-linux-gnu/release/igvmbuilder: No such file or directory
make: *** [Makefile:44: bin/coconut-qemu.igvm] Error 127
```

Makefile: respect `CARGO_ARGS` when building the igvmbuilder

---

src/cpu/percpu.rs
src/debug/stacktrace.rs
src/mm/stack.rs
src/mm/vm/mapping/kernel_stack.rs
src/task/tasks.rs
src/utils/memory_region.rs

The `StackBounds` type contains mostly a subset of the functionality of `MemoryRegion`, so simply remove the type and replace its uses. This makes the codebase more homogeneous and reduces code duplication.

mm/stack: remove the `StackBounds` type

---

Makefile

To support external workflows that are not incorporated into the makefile, publish the IGVM file builder to the bin directory so it can be consumed by those workflows.

Copy IGVM builder to bin directory

---

src/acpi/tables.rs
src/console.rs
src/cpu/cpuid.rs
src/cpu/insn.rs
src/cpu/percpu.rs
src/cpu/smp.rs
src/debug/gdbstub.rs
src/elf/mod.rs
src/fw_meta.rs
src/greq/pld_report.rs
src/greq/services.rs
src/lib.rs
src/locking/rwlock.rs
src/locking/spinlock.rs
src/mm/memory.rs
src/mm/pagetable.rs
src/mm/vm/mapping/api.rs
src/mm/vm/range.rs
src/serial.rs
src/sev/msr_protocol.rs
src/sev/status.rs
src/stage2.rs
src/string.rs
src/svsm.rs
src/svsm_paging.rs
src/utils/immut_after_init.rs

Since we are using the Rust 2021 edition, remove 2018 edition idioms. Add a lint to prevent future addition of these idioms.
Most of these changes are the addition of explicit lifetimes and removing `extern crate` statements where they were not needed.
Clippy would warn about these with:
```
cargo clippy --all-features -- -W rust-2018-idioms
```

Remove Rust 2018 edition idioms

---

src/cpu/vmsa.rs
src/sev/status.rs

Guest VMPLs will not enable exactly the same SEV features as SVSM VMPLs. In particular, guest VMPLs will not use restricted injection even if the SVSM does, and in the future, guest VMPLs may need to enable (or disable) other features such as alternate injection, REFLECT_VC, or vTOM.  This change refactors the determination of SEV features for guest VMPLs so that it is possible to change features in a robust way.
Note that this will become critical once QEMU begins loading the VMSA from the IGVM file, because the IGVM file specifies restricted injection which is not compatible with guest VMPL execution.

Ensure that guest VMPLs do not enable restricted injection

---

Makefile

In `stage1/stage1.S` we include `stage1/kernel.elf` but we don't have this dependency in the Makefile, so the build of `stage1/stage1.o` might fail if `stage1/kernel.elf` isn't built first.
Discovered by running `make -j10`:
$ make -j10
...
cc -c -o stage1/stage1.o stage1/stage1.S
stage1/stage1.S: Assembler messages:
stage1/stage1.S:82: Error: file not found: stage1/kernel.elf
make: *** [Makefile:95: stage1/stage1.o] Error 1

Makefile: add `stage1/kernel.elf` as a dependecy of `stage1/stage1.o`

---

kernel/src/mm/guestmem.rs

Multiple minor improvements, mainly to the `GuestPtr` type. This includes a fix for a potential undefined behavior issue when using `GuestPtr::offset()`.

mm/guestmem: multiple minor improvements

---

kernel/src/mm/pagetable.rs
kernel/src/stage2.rs

Fix a couple of nightly clippy warnings like the following:
```
warning: mutable reference of mutable static is discouraged
--> src/stage2.rs:69:50
|
69 |         bsp_percpu.set_pgtable(PageTableRef::new(&mut pgtable));
|                                                  ^^^^^^^^^^^^ mutable reference of mutable static
|
= note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
= note: reference of mutable static is a hard error from 2024 edition
= note: mutable statics can be written to by multiple threads: aliasing violations or data races will cause undefined behavior
= note: `#[warn(static_mut_ref)]` on by default
help: mutable references are dangerous since if there's any other pointer or reference used for that static while the reference lives, …
```

stage2: do not use mutable references to mutable statics

---

fuzz/fuzz_targets/fs.rs

Remove some leftover 2018 edition idioms in the fuzzing code.

fuzz: remove Rust 2018 edition idioms

---

Makefile

The binary targets generated by cargo must be listed as .PHONY targets to ensure that make knows to invoke cargo to force the targets to come up to date.  Without this, executing "make" will not reevaluate the Rust sources to determine whether rebuilds of the kernel or stage2 are necessary.

Fix incremental build

---

.github/workflows/rust.yml
scripts/pre-commit

During the switch to a workspace repository the clippy run on tests was removed, so add it again.
While we are at it, run clippy on `svsm-fuzz` only with `--cfg fuzzing`.

workflows: run clippy on tests

---

kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/vc.rs
kernel/src/debug/gdbstub.rs

The latest AMD SEV-SNP patch series for SEV-SNP enables the sev_features DEBUG_SWAP bit which delegates debug exceptions to the host rather than the guest VC handler. This patch adds a DB_VECTOR handler to allow these exceptions to be handled by the gdb stub when DEBUG_SWAP is set.

gdbstub: Add exception handler for DB_VECTOR for DEBUG_SWAP feature

---

Cargo.lock
igvmbuilder/Cargo.toml

Remove an unused dependency for igvmbuilder.

igvmbuilder: remove unused `bitflags` dependency

---

Cargo.lock
bootlib/Cargo.toml
bootlib/src/igvm_params.rs
igvmbuilder/src/igvm_builder.rs

Use zerocopy's `AsBytes` trait to get a byte representation of certain types where it is convenient. This requires deriving such trait in the bootlib crate.

igvmbuilder: avoid unsafe blocks

---

kernel/src/igvm_params.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_paging.rs

In Rust, references to `T` that are not aligned to that `T`'s requirements are undefined behavior. Check that the addresses obtained from the IGVM configuration are properly aligned before attempting to read the appropriate structures from them.
While we are at it, perform some minor code improvements.

igvm_params: avoid creating misaligned references and other small improvements

---

.github/workflows/rust.yml
Documentation/INSTALL.md
Makefile
stage1/reset.S
stage1/stage1.S

Besides being more consistent, this improves the process of performing a clean make ("make clean") because all generated targets are in one place and can be removed more consistently.
The "make clean" target contines to refer to the old files in the stage1 directory so that executing "make clean" after picking up this change will correctly remove the old files.

Move all generated binary targets to bin dir

---

Makefile
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/stage2_stack.rs

The IGVM builder does not yet package the filesystem image into the IGVM file for QEMU. Fix that and a couple of other small issues.

Igvmbuilder/fixes: Fix filesystem image packing/unpacking with IGVM

---

Documentation/INSTALL.md
Makefile
README.md
scripts/launch_guest.sh
scripts/test-in-svsm.sh

Coconut SVSM supports launch using two different custom builds of QEMU:
1. https://github.com/coconut-svsm/qemu/tree/svsm-v8.0.0 which contains a coconut SVSM specific launch protocol for the guest.
2. https://github.com/coconut-svsm/qemu/tree/svsm-igvm which supports launching a guest using IGVM.
The current installation instructions describe how to launch SVSM using 1. However, the plan is to move to only supporting IGVM. Therefore the documentaton has been updated to describe how to build an IGVM file containing SVSM/OVMF, build the required branch of QEMU and launch the guest.
The IGVM file packages SVSM with OVMF, therefore the item in the TODO list in README.md has been removed.
Note that the documentation refers to cloning and building the IGVM github repository. This currently …

Documentation: Update build/install instructions to use IGVM

---

kernel/src/debug/gdbstub.rs

Add some safety comments around pointer manipulation, fix a bug where the task ID was not taken into account when writing registers and other minor improvements.

gdbstub: take task ID into account when writing registers and other improvements

---

kernel/src/address.rs
kernel/src/config.rs
kernel/src/igvm_params.rs
kernel/src/svsm.rs

Introduce `VirtAddr::aligned_{ref,mut}` helpers to help transform a `VirtAddr` into a `&T` / `&mut T` while checking that the address is non-NULL and properly aligned to `T`'s requirements.
Also, add alignment check I missed in #226.

address: introduce more alignment check methods + add a missing alignment check

---

kernel/src/debug/gdbstub.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

Previously SVSM did not call the `init()` of serial port, thus did not set up the serial port. It worked fine with QEMU because QEMU's default serial port config complies with SVSM's usage. Google's hypervisor has different defaults, so it is necessary to initialize it.
Fix the problem by actually calling the `init()` at proper location.
Original patch by: Zixuan Wang <zxwang42@gmail.com>
Signed-off-by: Adam Dunlap <acdunlap@google.com>

console: Initialize serial port

---

Documentation/INSTALL.md
kernel/src/acpi/tables.rs

The Google hypervisor uses ACPI tables that are at a different path. The RSDP table also has extra information tacked onto the end. Allow passing the paths to these tables as environment variables and allow the RSDP table to be larger than expected.

acpi: Allow firmware path configuration

---

scripts/check-signed-off.sh

Instead of manually detecting merge commits to ignore them, simply use `git log --no-merges` directly.

scripts/check-signed-off: use `--no-merges` when listing commits

---

igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/stage2_stack.rs

* Remove a runtime size check in favor of a compile-time check
* Remove a needless allocation of a `Vec<u8>`.

igvmbuilder/stage2_stack: compile-time check stage 2 stack & remove needless allocation

---

bootlib/src/kernel_launch.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/stage2_stack.rs
kernel/src/config.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
stage1/stage1.S

This change includes the VTOM information in the boot stack because in certain circumstances, it may need to be available before the IGVM parameters are mapped.

stage2: Include VTOM in the stage2 boot stack

---

kernel/src/elf/mod.rs

Fix the following clippy warning on the nightly toolchain:
```
error: unnecessary qualification
--> kernel/src/elf/mod.rs:2539:29
|
2539 |         assert_eq!(res, Err(crate::elf::ElfError::InvalidPhdrSize));
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: requested on the command line with `-D unused-qualifications`
help: remove the unnecessary path segments
|
2539 -         assert_eq!(res, Err(crate::elf::ElfError::InvalidPhdrSize));
2539 +         assert_eq!(res, Err(ElfError::InvalidPhdrSize));
|
```

elf/tests: remove unnecessary qualification

---

igvmbuilder/src/gpa_map.rs

In the Hyper-V configuration, the IGVM builder places the kernel image just above the firmware image.  If there is no firmware image, this results in the kernel image being placed at address zero.  This overlaps with where stage 2 is loaded, and that results in corruption of the kernel image and/or the IGVM parameter block depending on the extent of the collision.  Moving the kernel to a minimum address of 1 MB ensures that there is no collision.

Fix Hyper-V IGVM without firmware

---

kernel/src/cpu/insn.rs
kernel/src/cpu/vc.rs
kernel/src/mm/guestmem.rs

Faults can happen in the #VC handler if the exception context RIP (more generally the [RIP; RIP+15] array) doesn't belong to a mapped page.
To handle these faults, we can rely on GuestPtr::read() that uses the exception table if a fault occurs.
This touches the #VC handler, so I would wait for #288 to be merged to correctly test this PR.

cpu/vc: handle faults when fecthing instructions

---

bootlib/src/kernel_launch.rs
igvmbuilder/src/gpa_map.rs
kernel/src/config.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_paging.rs

Certain hypervisors today impose a restriction that a VMSA page cannot be aligned to a 2 MB boundary.  This change adjusts the layout of the SVSM physical memory block so the VMSA is located at the top, not the base.

kernel: Change the location of the VMSA page

---

kernel/src/console.rs
kernel/src/cpu/smp.rs
kernel/src/mm/pagetable.rs
kernel/src/utils/immut_after_init.rs

The initialization of `ImmutAfterInitCell` objects (and, by extension, `ImmutAfterInitRef` objects) is designed specifically only to safe when the system is still in a single-threaded environment, because the intialization checks are not thread-safe.  This change ensures that no attempt is made to initialize or reinitialize any of these objects once the system has started multiple processors.  These checks are debug-only, like the checks on initialization state.

Prevent use of ImmutAfterInit in the multithreaded environment

---

kernel/src/cpu/idt/stage2.rs
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/vc.rs

Remove calls to `Result::expect()` in the VC code and return errors so that they can be handled by callers.
`VcError` is already implemented, so use the already existing type. Introduce `VcError::new()` to improve ergonomics when creating a new error.

cpu/vc: improve error handling

---

kernel/src/cpu/msr.rs
kernel/src/cpu/vc.rs
kernel/src/sev/utils.rs
scripts/launch_guest.sh

Adds tests that make sure a \#VC exception is raised while executing various instructions and that the #VC handler properly handles them via the ghcb. Instructions tested are cpuid and port IO.
Looking for feedback on the following:
- Is the raw-cpuid dependency OK, or would it be better to just use inline asm or something else?
- What's a good location to put these? I chose ghcb.rs, but they might make more sense somewhere else.
- I have tests for other \#VC handler cases such as ones for msrs, dr7, wbinvd, rdtsc, mmio, and other IOIO instructions, but they fail since those cases aren't handled in the svsm handler. I could add these as \#\[should_panic\] if we think they might be useful later.
- I did not test these with qemu since it doesn't work on hardware I have. The IOIO tests rely …

sev/ghcb Add #VC handler tests

---

kernel/src/utils/util.rs

Do not only make these helpers work on usize, but on any type supporting the required operations. Also implement page_align_up() in terms of align_up().

kernel/utils: Make align_up/down helpers generic

---

kernel/src/debug/gdbstub.rs

The latest cargo release v1.77.0 is generating a warning for the "&mut PACKET_BUFFER", failing our github CI.
```
error: creating a mutable reference to mutable static is discouraged
--> kernel/src/debug/gdbstub.rs:52:37
|
52 |                 .with_packet_buffer(&mut PACKET_BUFFER)
|                                     ^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
```
Although it says that creating a mutable reference to mutable static is discouraged, this is the only place we use the PACKET_BUFFER variable and so it seems safe.
This PR overrides "-D warnings" by adding
"#[allow(static_mut_refs)]". That will force us to update our installed cargo to latest, otherwise, an error message like "unknown lint" will be printed.

kernel/gdbstub.rs: Allow mutable reference to mutable static

---

kernel/src/stage2.rs
kernel/src/utils/mod.rs
kernel/src/utils/util.rs

Add a check to make sure that the offset between the physical addresses and the virtual mapping is aligned to 2MiB.

stage2: Check for correct alignment of virtual offset

---

Documentation/INSTALL.md

In the QEMU's `svsm-igvm` branch that we recommend using, we moved to
QEMU v8.2.0 which wants slightly different parameters as we already
have in the `scripts/launch_guest.sh` script.
So let's also update INSTALL.md with these new parameters and also fix
`launch_guest.sh` example adding the missing `.sh` extension.

Documentation: update QEMU v8.2.0 parameters and fix launch_guest.sh example

---

kernel/src/error.rs
kernel/src/mm/pagetable.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

This reverts commit 55b350a81a9156bad55da6f6e0799ae3755c5bce.
Latest upstream branch did not boot anymore beyond stage2. Bisection pointed to above commit and reverting it fixes the issue. It is quite possible the above commit uncovered another issue, but for now keep things booting and revert it until the underlying issue has been fixed.

Revert "mm/pagetable: add module-level error handling"

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
Makefile
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/vmsa.rs
igvmmeasure/.cargo/config.toml
igvmmeasure/Cargo.toml
igvmmeasure/README.md
igvmmeasure/src/cmd_options.rs
igvmmeasure/src/igvm_measure.rs
igvmmeasure/src/main.rs
igvmmeasure/src/page_info.rs

This PR introduces a new tool `igvmmeasure` that parses an IGVM file and calculates the launch digest which should match the launch measurement included as part of the attestation report from the platform.
By introducing this tool, it created the opportunity to verify that the directives within the IGVM file produced by the build process are properly sent as initial guest state, exactly as described and in the correct order. It was found that there were some discrepancies between the current IGVM file and the QEMU loader/KVM launch process that resulted in a mismatch between the expected and actual digest.
The first two commits in this PR fix these issues which both relate to the VMSA then proceed to introduce the measurement tool and introduce it into the build. An option has also been …

Ensure IGVM output is compatible with QEMU and calculate launch measurement

---

kernel/src/error.rs
kernel/src/fw_meta.rs
kernel/src/svsm.rs

Return errors from leaf functions and panic at the callers in `svsm_main()`. While we are at it, handle these errors with `Result::expect()`, which will print the originating `SvsmError`.

svsm: improve error handling during firmware configuration

---

kernel/src/protocols/core.rs
kernel/src/requests.rs

In the SVSM protocol, requests are serviced by reading and writing to a structure shared with the guest. The fields of this structure fit into a `u64`, so we were using that up until now. In order to improve readability and future mistakes, add a proper type for this structure.

svsm/requests: introduce the `SvsmCaa` type

---

Makefile

Use the already existing `CARGO_ARGS` in the Makefile when running tests, as there are  situations where one may want to pass additional flags to "cargo test", like building the tests in release mode.

Makefile: respect `CARGO_ARGS` when running tests

---

Makefile

The svsm module in kernel/ builds both the stage2 and kernel binaries. This can be configured with enable-gdb and mstpm features, both of which only apply to the kernel binary and not stage2. However the current Makefile enables the same features set for both binary builds.
The linker would normally remove the unused code generated for the features but, for mstpm the linker leaves a large amount of dead code in stage2. This causes the link to fail as stage2 does not link against libmstpm.
This commit changes the Makefile to remove all default features when building stage 2. In order to do this, it must run the cargo build directly on the kernel Cargo.toml.
This addresses https://github.com/coconut-svsm/svsm/issues/313

Makefile: Exclude default features when building stage2

---

libmstpm/deps/openssl_svsm.conf

When OpenSSL is compiled with any optimization (e.g. -O1), the gcc generates code with instructions that are not supported at the SVSM level (e.g. the SSE pxor). That crashes the SVSM boot with an unhandled exception 6 (invalid opcode), usually in:
vtpm_init()->libtpm:manufacture()->libcrypto:BN_CTX_new(). For example:
[SVSM] Launching request-processing task on CPU 3
[SVSM] FW Meta Data
[SVSM]   CPUID Page   : 0x0080e000
[SVSM]   Secrets Page : 0x0080d000
[SVSM]   CAA Page     : 0x0080f000
[SVSM]   Pre-Validated Region 0x0000000000800000-0x0000000000809000
[SVSM]   Pre-Validated Region 0x000000000080a000-0x000000000080d000
[SVSM]   Pre-Validated Region 0x0000000000810000-0x0000000000820000
[SVSM] Validating 0x0000000000800000-0x0000000000809000
[SVSM] Validating …

Fix SVSM boot crash when RELEASE=1

---

kernel/src/cpu/ghcb.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/cpu/vc.rs
kernel/src/debug/stacktrace.rs
kernel/src/protocols/core.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

This PR changes the implementation of CPU borrow checking in two important ways.  First, it uses `RefCell` instead of a custom implementation of borrow checking - this is valuable because it relies on core common code.  Second, borrow checking is now performed in all builds, not just debug builds - this is important because the memory safety guarantees made by Rust are intended to apply in all cases, in all code paths, not just those code paths that were validated using debug builds.
The contents of `PerCpu` have been refactored to enforce meaningful borrow checking according to a specific set of principles.
- In general, *all* references to a structure must enforce borrow checking rules to prevent conflicts between shared and mutable references.
- When references are synthesized from …

kernel/cpu: overhaul per-CPU borrow checking

---

kernel/src/lib.rs
kernel/src/protocols/mod.rs
kernel/src/requests.rs
kernel/src/svsm.rs

Do not try to build the vTPM bindings into the test-in-svsm binary. This causes linker errors and there are not TPM tests yet anyway.

kernel: Build test-kernel without TPM support

---

.gitignore
Cargo.lock
Cargo.toml
Makefile
igvmbuilder/README.md
igvmbuilder/src/cmd_options.rs
igvmbuilder/src/igvm_builder.rs
igvmmeasure/Cargo.toml
igvmmeasure/README.md
igvmmeasure/src/cmd_options.rs
igvmmeasure/src/id_block.rs
igvmmeasure/src/igvm_measure.rs
igvmmeasure/src/main.rs
igvmmeasure/src/page_info.rs
igvmmeasure/src/utils.rs
scripts/gen_igvm_signing_keys.sh
scripts/test_sign_qemu_igvm.sh

The `igvmmeasure` tool was previously introduced to calculate and display the expected launch measurement for an IGVM file on a particular platform. The next progression is to embed that launch measurement into an SNP ID block so that an IGVM loader implementation on a hypervisor can provide this at guest startup to prevent launch if the IGVM file has been tampered with. This information also forms part of the attestation report and can be used to remotely verify the integrity of the initial guest state.
Generation of an ID block requires the launch measurement to be signed using a private key. Initial work on this PR involved reworking `igvmmeasure` into a separate library and executable so the ID block generation could be performed in `igvmbuilder`. However, this would require private …

Extend IGVM measure tool to generate SEV-SNP ID blocks containing signed launch measurement

---

.gitmodules
libmstpm/Makefile

Point the TPM dependency to a COCONUT-specific fork of the Microsoft TPM reference implementation. The fork has some changes on-top of the upstream TPM library which are required in the SVSM environment.

Update URL to libmstpm/deps/ms-tpm-20-ref

---

fuzz/fuzz_targets/insn.rs
kernel/src/cpu/insn.rs
kernel/src/cpu/vc.rs
kernel/src/sev/ghcb.rs
kernel/src/svsm.rs

* Simplify the instruction decoder and its API.
* Decode remaining `IN` / `OUT` instruction cases and enable related #VC tests.
* Handle `SVM_EXIT_MSR` in the #VC handler and enable related #VC tests.
* Support SVSM discovery via MSR for post-boot services.
* Support SVSM discovery via CPUID for post-boot services.
This works towards a more complete implementation of #14

cpu/vc: improve instruction decoder + handle more `IN` / `OUT` instructions + handle `RDMSR` / `WRMSR` + add SVSM discovery support

---

Cargo.lock
Cargo.toml
kernel/Cargo.toml
kernel/src/greq/msg.rs
kernel/src/greq/pld_report.rs
scripts/test-in-svsm.sh

As of Rust 1.77, the `core::mem::offset_of!()` macro is stable, which means we no longer need to use the `memoffset` crate in tests. The new  macro is also more efficient as it does not have excessive stack usage, which means we can enable the tests that make use of this macro inside the SVSM.
While we are at it, remove an unnecessary check in `scripts/test-in-svsm.sh`.

test: remove `memoffset` dependency

---

kernel/src/mm/alloc.rs
kernel/src/vtpm/mstpm/wrapper.rs

* Remove `mem_allocate()`, `mem_reallocate()` and `mem_deallocate()`, as they simply duplicate the functions in the alloc library (`alloc::alloc::{alloc, realloc, dealloc}`).
* Hold the root memory lock for the whole duration of `layout_from_ptr()`. Otherwise the pointer in the slab page info could be invalidated concurrently.

mm/alloc: remove allocator wrappers and fix a soundness issue

---

kernel/build.rs

Currently, running `make` after changing a linker script does not run a new build, which is counterintuitive. Let cargo now that if at least one of the linker scripts changes, we want to build the kernel again.

kernel/build.rs: run build if linker scripts changed

---

kernel/src/cpu/insn.rs
kernel/src/cpu/msr.rs
kernel/src/cpu/vc.rs
kernel/src/sev/ghcb.rs

* Add GHCB getters and setters that check or set the valid bitmap (now that there's a stable `offset_of!()` macro).
* Fix potential problem with `GHCB::rdmsr_regs()`.
* Implement `RDTSC` #VC handler and enable relevant in-SVSM test.
* Fix `rdtscp()`.
* Implement `RDTSCP` #VC handler and enable relevant in-SVSM test.
* Add a test for the GHCB layout.
This works towards a more complete implementation of #14 .

cpu/vc: implement `RDTSC` and `RDSTCP` #VC handlers

---

Cargo.lock
Cargo.toml
Makefile
bootlib/src/kernel_launch.rs
bootlib/src/lib.rs
bootlib/src/platform.rs
igvmbuilder/src/cmd_options.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/main.rs
igvmbuilder/src/platform.rs
igvmbuilder/src/stage2_stack.rs
igvmbuilder/src/vmsa.rs
kernel/src/boot_stage2.rs
kernel/src/cpu/cpuid.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/lib.rs
kernel/src/mm/pagetable.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_console.rs
stage1/stage1.S

This change defines a platform abstraction to permit the SVSM to execute correctly on multiple platform types.  The first additional platform type is the "native" platform, meaning a VM that is not isolated with SNP, which runs as a native VM type on its host.  This change is only sufficient to boot the SVSM on a native platform through stage 2 into the kernel, and additional native support will be added in the future.

Support multiple platforms in the SVSM

---

igvmbuilder/src/vmsa.rs

EFER.SVME is specific to the AMD virtualization architecture (just as CR4.VMXE is specific to Intel).  It should not be included in a CPU context that purports to work on any native x86-64 host architecture.

igvmbld: Do not include EFER.SVME for NATIVE platforms

---

kernel/src/console.rs
kernel/src/debug/gdbstub.rs
kernel/src/serial.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

* serial: make `SerialPort` fields private and use `SerialPort::new()` where needed.
* serial: add `SerialPort::{inb, outb}()` to simplify code.
* console: remove `Option` from `Console`, as it is always `Some`.
* console: initialize `WRITER` directly from `init_console()`
* console: return error from `install_console_logger()` instead of implicitly panicking.

console, serial: multiple cleanups

---

kernel/src/cpu/gdt.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/percpu.rs
kernel/src/fw_meta.rs
kernel/src/locking/spinlock.rs
kernel/src/mm/alloc.rs
kernel/src/sev/secrets_page.rs
kernel/src/string.rs
kernel/src/svsm_console.rs
kernel/src/task/schedule.rs
kernel/src/task/waiting.rs
kernel/src/vtpm/mstpm/mod.rs

Fix several warnings like the following, either by implementing Default manually or by deriving it:
```
error: you should consider adding a `Default` implementation for `SVSMIOPort`
--> kernel/src/svsm_console.rs:18:5
|
18 | /     pub const fn new() -> Self {
19 | |         SVSMIOPort {}
20 | |     }
| |_____^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
help: try adding this
|
17 + impl Default for SVSMIOPort {
18 +     fn default() -> Self {
19 +         Self::new()
20 +     }
21 + }
|
```

svsm: fix clippy warnings

---

fuzz/Cargo.toml
kernel/src/vtpm/mstpm/mod.rs

Do not use the default features when building the SVSM for fuzzing, as linking `libmstpm` breaks the fuzzers.

fuzz: do not use default features when building the SVSM

---

fuzz/fuzz_targets/page_alloc.rs
kernel/src/mm/alloc.rs

* Store the slab item size instead of the slab pointer in the page info. This simplifies `layout_from_ptr()` and the initialization of several structures.
* Track slab item sizes at compile time via const generics. This removes several runtime fields in a couple of structures and simplifies initialization further.

mm/alloc: track slab item sizes at compile time

---

kernel/src/fw_meta.rs
kernel/src/greq/msg.rs
kernel/src/mm/page_visibility.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/sev/ghcb.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_paging.rs

* Replace `start` + `end` function parameters with `MemoryRegion` parameters.
* Replace bool parameters for `SvsmPlatform` methods with enums.
* Use `SvsmPlatform` page state change methods in several places instead of directly calling into the `GHCB` or `PVALIDATE`.

Use `SvsmPlatform` page state change methods and other cleanups

---

Makefile
kernel/Cargo.toml
kernel/build.rs
kernel/src/debug/gdbstub.rs

* Remove the `default-test` feature: it is not really needed, as we can detect if we're building tests via the "test" cfg.
* Remove a nightly clippy warning in the gdbstub code.

svsm: remove `default-test` feature & fix leftover nightly clippy warning

---

Cargo.lock
Cargo.toml
kernel/Cargo.toml
kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/stage2.rs
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/cpu/vc.rs
kernel/src/mm/page_visibility.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/requests.rs
kernel/src/sev/ghcb.rs
kernel/src/sev/hv_doorbell.rs
kernel/src/sev/mod.rs
kernel/src/svsm.rs
kernel/src/task/tasks.rs

This PR adds the required logic to support restricted injection of interrupts via the #HV protocol.  No interrupt handlers are defined in this PR.

kernel: Support restricted injection

---

igvmbuilder/Cargo.toml
igvmmeasure/Cargo.toml

When a dependency is used by multiple packages, Cargo will use the union of all features enabled on that dependency when building it. See https://doc.rust-lang.org/cargo/reference/features.html#feature-unification for more details.
These two crates are tools, so let's specify dependencies only for `target_os = "linux"`. This way these dependencies (which can use `std` for example) are not unified with those of SVSM, producing build errors as reported in https://github.com/coconut-svsm/svsm/pull/345

igvm*: specify dependencies' target to avoid feature unification

---

kernel/src/mm/page_visibility.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/stage2.rs
kernel/src/svsm_paging.rs

This change separates page validation and invalidation into separate methods to avoid reliance on any platform-specific operation types.  This will further facilitate platform abstractions for platforms that do not treat validation and invalidation as symmetric operations.

platform: separate validate/invalidate method calls

---

kernel/src/mm/pagetable.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

Return possible errors from `paging_init()` and `paging_init_early()` and let callers handle them.

mm/pagetable: return errors instead of implicitly panicking

---

Documentation/docs/developer/DEVELOPMENT-PLAN.md

Tracking the unsound code patterns with issue #359, and set new owners to Carlos López, Thomas Leroy and Tom Dohrmann.

docs: add owners of the unsound code patterns item

---

fuzz/fuzz_targets/insn.rs
kernel/src/cpu/control_regs.rs
kernel/src/cpu/gdt.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/mod.rs
kernel/src/cpu/registers.rs
kernel/src/cpu/vc.rs
kernel/src/error.rs
kernel/src/insn_decode/decode.rs
kernel/src/insn_decode/insn.rs
kernel/src/insn_decode/mod.rs
kernel/src/insn_decode/opcode.rs
kernel/src/lib.rs
kernel/src/sev/ghcb.rs
kernel/src/types.rs

This pull request introduces the kernel/insn_decode crate, which provides instruction decoding capabilities. It is implemented by referring the [ instruction decoder](https://github.com/projectacrn/acrn-hypervisor/blob/master/hypervisor/arch/x86/guest/instr_emul.c) from the ACRN project. As an acknowledgment, its copyright notice has been included in the header of decode.rs.
Upon a successful decoding for a given set of instruction bytes, a DecodedInsnCtx is created, containing detailed decoding outcomes. This structure exposes two public interfaces that allow access to the corresponding DecodedInsn and the decoded instruction length.
Currently, the crate supports decoding for the in/out, rdmsr, wrmsr, rdtsc, rdtscp, and cpuid instructions, which are essential for the current SEV #VC …

Add a separate crate insn_decode in kernel for instruction decoding

---

igvmbuilder/src/cmd_options.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/vmsa.rs
igvmmeasure/src/igvm_measure.rs

The latest versions of KVM patches (not yet upstream) set `debug_swap` to false by default. Also being a debug feature, we don't expect it to be enabled in production, so let's disable it to avoid difference between the launch measurement at runtime and the pre-calculated one.
The latest patch adds a new option to check debugging features like SNP debug_swap, but I'm not sure it's needed.
Any comments are welcome!
Tested with one patch on top to print the launch measurement (https://github.com/stefano-garzarella/svsm/tree/get_report_fixed):
```
$ make
...
"target/x86_64-unknown-linux-gnu/debug/igvmmeasure" --check-kvm bin/coconut-qemu.igvm measure
===============================================================================================================
igvmmeasure …
```

igvm tools: fix pre-calculated launch measurement with QEMU/KVM

---

Documentation/docs/developer/DEVELOPMENT-PLAN.md

Add myself as the owner of items related to bringing up SVSM on TD Partitioning platforms:
- Igvm
- TdxSmp
- Boot

docs: add owner to TDP enabling items

---

Documentation/docs/developer/DEVELOPMENT-PLAN.md

- The initial PR([358](https://github.com/coconut-svsm/svsm/pull/358)) of InstrDec support patches have been submitted from my side, which is to support the instructions used by #VC handlers. The more complex instructions ins/outs/mov will be supported in the future, which is also part of my plans.
- Add myself as the owner of the TdxParaV item, which will implement the TDX paravisor in both the user mode and the kernel mode.

docs: add myself as owner of InstrDec and TdxParaV

---

kernel/src/sev/ghcb.rs

* `GHCB::write_buffer()` had several soundness issues, so fix them:
* Computing the destination pointer could overflow.
* The resulting pointer could be misaligned.
* The specified  `T` needed to be `Copy`.
* There is no reason to use associated constants for `GHCBExitCode` values, so simply use enum variants with defined discriminants.

sev/ghcb: fix `GHCB::write_buffer()` soundness issues and clean up `GHCBExitCode`

---

kernel/src/cpu/gdt.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/stage2.rs
kernel/src/cpu/idt/svsm.rs

When running the LIDT or LGDT instructions, we pass addresses pointing to architecture-specific tables that the CPU will use during operation. These tables must reside on valid memory during CPU operation to avoid malfunction.
In practical terms, this means the GDT and IDT entries must have a `static` lifetime. This will avoid at compile time the following construct:
```rust
{
let idt = IDT::new();
idt.load();
}
// the IDT entries are no longer valid here
```
We could enforce this at the type level by requiring the `load()` method on these structs to take a `&'static lifetime`. However, since we use locking, we cannot get such reference, only a reference that lives as long as a lock guard we get from the lock protecting the struct. However, this does not matter, as we can check that the …

cpu: fix IDT and GDT lifetimes on load methods

---

kernel/src/platform/snp.rs

The physical address sizes come from cpuid Fn8000_0008_EAX but due to a variable shadowing problem, when vtom was disabled it was instead taking it from cpuid Fn8000_001F_EAX.
Fixes: edf38b0c7f ("platform: Calculate PTE masks through platform abstraction")

platform: Get correct phys addr sizes when not using vtom

---

Cargo.lock
Cargo.toml
igvmbuilder/src/vmsa.rs

Update crate dependencies to current upstream versions:
- **Upgrade igvm to 0.3.2**
- **Upgrade bitfield-struct to 0.6.2**

Update Crate Dependencies

---

Documentation/docs/developer/DEVELOPMENT-PLAN.md

- Add myself as the owner of the ApicEmul item, to add vXAPIC and vX2APIC support for TD partitioned guest.
@msft-jlange Please let me know if you plan to work on this item and we can co-own this item.

docs: add owner of ApicEmul item

---

igvmbuilder/src/cmd_options.rs
igvmbuilder/src/vmsa.rs
kernel/src/sev/status.rs
kernel/src/svsm.rs

* Add missing SEV feature definitions to the kernel and igvmbuilder.
* Get SEV features via the platform API
* Check SEV features in the SVSM kernel again, since we reload them.
* Dump CPUID table after logging is enabled.
* Initialize `reg_prot_nonce` if `VmsaRegProt` is enabled.

svsm: drop `VmsaRegProt` support, add missing SEV features and other improvements

---

bootlib/src/platform.rs
igvmbuilder/src/stage2_stack.rs
kernel/src/error.rs
kernel/src/stage2.rs
kernel/src/utils/memory_region.rs

`stage2_main()` was very long and plagued with spread out panics in different places. Split out functionality into separate functions, each returning an error, and panic at the top level.
While we are at it, clean up the kernel layout logic, using the `MemoryRegion` type and updating the loaded region at each stage. Add documentation on each step for clarity.
Finally, add a missing check in the new `prepare_heap()` function to verify that we did not exceed the reserved kernel region size.

stage2: refactor stage2

---

.gitignore

The bin/ and target/ directories in the repo-relative root are irrelevant to change management, but vendor/*/src/{bin,target} are relavent to checked-in repos that use `cargo vendor` to track dependendies.

Only ignore the top level bin and target dirs

---

bootlib/src/igvm_params.rs
igvmbuilder/src/igvm_firmware.rs
kernel/src/config.rs
kernel/src/igvm_params.rs
kernel/src/mm/memory.rs
kernel/src/svsm.rs

This change permits the SVSM kernel to adjust the memory map according to its own needs before passing it to the guest firmware.  This is necessary in case the SVSM requires additional memory beyond the SVSM carveout based on runtime state, such as the total amount of memory in the VM.  The memory map is presented in IGVM format, and its location is specified in the IGVM parameters established when the SVSM IGVM file is built.

svsm: pass the memory map to guest firmware

---

igvmbuilder/src/gpa_map.rs

The firmware field of GpaMap was initialized once but never read. This raises a warning in the last clippy release.

igvmbuilder: remove firmware field in GpaMap

---

Documentation/docs/installation/INSTALL.md

The OVMF variable is now unnecessary since the firmware will eventually be embedded in the IGVM file.
Let's also add a note to clarify that we need to install the target `x86_64-unknown-none` for the nightly toolchain to avoid the following error:
$ QEMU=/path/to/qemu-system-x86_64 make test-in-svsm
...
LINK_TEST=1 cargo +nightly test  -p svsm --config 'target.x86_64-unknown-none.runner=["sh", "-c", "cp $0 ../target/x86_64-unknown-none/debug/svsm-test"]'
error[E0463]: can't find crate for `core`
|
= note: the `x86_64-unknown-none` target may not be installed
= help: consider downloading the target with `rustup target add x86_64-unknown-none`
= help: consider building the standard library from source with `cargo build -Zbuild-std`

INSTALL.md: fix unit tests instructions

---

Makefile
bootlib/src/igvm_params.rs
bootlib/src/platform.rs
igvmbuilder/src/cmd_options.rs
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/ovmf_firmware.rs
igvmbuilder/src/stage2_stack.rs
kernel/src/error.rs
kernel/src/platform/mod.rs
kernel/src/platform/tdp.rs
stage1/stage1.S

This is the first set of patches to begin supporting TD Partitioning in the IGVM framework. Patches for TDX enabling will follow.
No changes to the IGVM spec are proposed yet. The goal is to allow TDP enabling to hit the ground running first.
The main work in this patchset is to separate TDP from SEV platforms.
To generate an IGVM file for a TDP platform as part of the build process, run:
`$ make PLATFORM=tdp FW_FILE=/path/to/OVMF.fd`

igvm: initial support for TD Partitioning

---

kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/sev/ghcb.rs
kernel/src/sev/hv_doorbell.rs

* Store a safe reference to the HV doorbell in the PerCpu
* Cleanups and add some documentation
* Store a safe reference to the SVSM VMSA in the PerCpu

cpu/percpu: store safe references to HV doorbell page and SVSM VMSA

---

Cargo.toml

The lint is currently broken on nightly and causes in-SVSM tests to fail, so just remove it for now.

clippy: remove unused-qualifications lint

---

Cargo.lock
Cargo.toml
igvmmeasure/Cargo.toml
igvmmeasure/src/cmd_options.rs
igvmmeasure/src/id_block.rs
igvmmeasure/src/igvm_measure.rs
igvmmeasure/src/main.rs
igvmmeasure/src/page_info.rs

This PR adds implements calculation of the expected launch measurement for IGVM files that target the SEV and SEV-ES platforms.
Although not needed for COCONUT-SVSM itself as this always requires SEV-SNP, these changes are required to support the testing of the QEMU IGVM patch series, which supports all flavours of SEV.
As part of this, the create previously used for the SHA-384 implementation has been replaced with the RustCrypto equivalent. As well as providing SHA-256 implementation as part of the same library (which the previous one did not), this provides consistency in use of RustCrypto with other cryptographic crates we are already using in COCONUT.

igvmmeasure: Implement launch measurement calculation for SEV and SEV-ES

---

kernel/src/cpu/apic.rs
kernel/src/cpu/vc.rs
kernel/src/debug/gdbstub.rs
kernel/src/igvm_params.rs
kernel/src/mm/guestmem.rs
kernel/src/protocols/core.rs
kernel/src/protocols/vtpm.rs
kernel/src/requests.rs
kernel/src/sev/secrets_page.rs
kernel/src/svsm.rs

Leaving as draft because I still have doubts.
Providing partial fix for #359 (tasks 7, 8, 9).
My two interrogations are:
1. There are several uses of the following pattern:
```rust
let guard = PerCPUPageMappingGuard::create_4k(paddr)?; // paddr possibly guest or HV controlled
let start = guard.virt_addr();
let guest_page = GuestPtr::<Tt>::new(start + offset);
let mut request = unsafe { guest_page.read()? };
``` 
As already discussed with @00xc, if `start + offset` is valid but `start + offset + size_of::<T>` ends on an unmapped page or on an adjacent page belonging to another guest or the SVSM kernel (I don't really know if it's possible), `read()` could raise a #PF and possibly return an error and panicking, or reading content from an unauthorized page. If such scenarii are possible, we …

Make read/write methods from GuestPtr unsafe, and copy_{from, to} methods from SecretsPage as well 

---

kernel/src/cpu/percpu.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/protocols/apic.rs

The current Alternate Injection specification describes the use of a count-based registration mechanism for tracking the enablement of APIC emulation, but the previous implementation of the code use the older locking-based design.  The code must be revised to match the current spec.

protocols/apic: update the registration-based APIC protocol

---

kernel/src/cpu/apic.rs
kernel/src/cpu/percpu.rs
kernel/src/error.rs
kernel/src/platform/snp.rs
kernel/src/protocols/apic.rs
kernel/src/protocols/errors.rs

This change removes `ApicError` as a type associated with APIC emulation and defines it as a subordinate type of `SvsmError`, with variants describing the types of errors that may be associated with APIC handling (emulation or otherwise).  This permits unification of error types across different components so they can all use `SvsmError`.

error: subsume ApicError into SvsmError

---

kernel/src/greq/msg.rs

Now that the `offset_of` macro is stable, simply use it to get the desired offset for the slice. Simplify also the slice creation by simply casting a `*const Self` to a `*const u8` and calling `slice::from_raw_parts` with the adequate size.

greq/msg: simplify `SnpGuestRequestMsgHdr::get_aad_slice()`

---

kernel/src/boot_stage2.rs

TDX does not permit writing to the EFER register.  Instead, EFER.LME is set as part of the reset state so long mode can be activated once paging is enabled.  Since EFER.LME is already set by the hardware, any attempt to set EFER.LME should not write the EFER MSR if EFER.LME is already set.

boot_stage2: avoid modifying EFER if possible

---

kernel/src/mm/page_visibility.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/ptguards.rs

Document memory management of page tables, page visibility and per-CPU mapping guards. This is related to issue https://github.com/coconut-svsm/svsm/issues/74 Document COCONUT-SVSM and continues the mm documentation efforts that started with the merged https://github.com/coconut-svsm/svsm/pull/243. For the purpose of that issue, I will consider the memory subsystem sufficiently documented after this PR (even if not every single detail has been documented) and would like to shift focus to documenting `protocols`.

docs: Document page tables, visibility, per-CPU guards

---

libmstpm/Makefile
libmstpm/deps/libcrt/Makefile
libmstpm/deps/openssl_svsm.conf

As reported by Jiewen Yao, OpenSSL is built using a stack red zone, which causes issues when returning from an interrupt. Disable it in the OpenSSL build flags, as well as in libmstpm and libcrt.
Fixes: #404

libmstpm: disable red zone

---

kernel/src/platform/snp.rs

The current logic for enabling alternate injection is broken, as it will enable it always. This is causing a crash during boot when running under a hypervisor that does not support the feature:
```
[SVSM] ERROR: Panic: CPU[0] panicked at kernel/src/svsm.rs:449:36:
Failed to setup guest VMSA/CAA: Ghcb(VmgexitError(2, 6))
[SVSM] ---BACKTRACE---:
[SVSM]   [0xffffff8000128445]
[SVSM]   Invalid frame
[SVSM] ---END---
```
Fix this by checking upfront if the feature was requested.
Fixes: 978aef5a9d75 ("protocols/apic: update the registration-based APIC protocol")

platform/snp: enable alternate injection only if requested

---

kernel/src/cpu/percpu.rs
kernel/src/error.rs
kernel/src/protocols/apic.rs
kernel/src/protocols/errors.rs

Introducing `Disabled` to `SvsmError(Apic)` simplifies error handling in many of the paths that involve determining whether APIC emulation is active.

errors: introduce APIC disabled error

---

kernel/src/console.rs
kernel/src/error.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

On platforms that do not require extensive platform setup (e.g. GHCB) for console output services, initialize the console logger as early as possible to facilitate earlier logging of initialization activity.

svsm: permit early initialization of console logging

---

cpuarch/src/vmsa.rs

Add missing VMSA fields as of the latest revision in the AMD manual. While we are at it, verify at compile-time that the VMSA size is exactly that of one page.

cpuarch/vmsa: add missing VMSA fields

---

stage1/reset.S
stage1/stage1.S

This set of patches enables TDX in stage1 trampoline-only mode. This includes bootstrapping from the reset vector in protected non-paged mode, performing sanity checks, and setting up the ESP register.

stage1: add TD Partitioning support

---

kernel/src/boot_stage2.rs

This is the first half of the TDX enabling work in stage2. It focuses on boot_stage2.rs, before reaching stage2_main(). The main goal of this patchset is to lay the groundwork for TD SMP support. TD SMP boot flow is different from traditional x86 SMP in that all TD vCPUs start execution in 32-bit non-paged mode concurrently and the INIT/SIPI protocol is not used.

stage2: add TD Partitioning support to boot_stage2

---

Cargo.toml

Do not require `Copy` for all structures that can derive it, as this can be error prone and can inadvertently increase stack usage. For now, remove the related lint, as introducing `Copy` for in the future should not require too much work if necessary.

workspace: remove `missing_copy_implementations` workspace lint

---

kernel/src/cpu/percpu.rs
kernel/src/mm/alloc.rs
kernel/src/mm/mod.rs
kernel/src/mm/pagebox.rs
kernel/src/mm/pagetable.rs
kernel/src/sev/ghcb.rs
kernel/src/sev/hv_doorbell.rs
kernel/src/sev/vmsa.rs

* Introduce a `PageBox<T>` type. It works like `Box<T>`, releasing memory on drop, but it only has a subset of the functionality and uses memory obtained directly from the page allocator. This is useful for some types that need to reside on a page of their own.
* Introduce a `VmsaPage` abstraction based on the `PageBox` type.
* Introduce a `HVDoorbellPage` abstraction based on the `PageBox` type.
* Introduce a `GhcbPage` abstraction based on the `PageBox` type.
* Update the `PerCpu` code to use the `PageBox` type.
* Update the pagetable code to use the `PageBox` type.

Introduce safe page allocation abstractions

---

igvmbuilder/src/cpuid.rs

The IGVM file specifies the set of CPUID leaves that are expected to be provided when the IGVM file is loaded.  The builder was erroneously specifying leaf EAX=1 with subleaf ECX=1, which is not architecturally defined.  This caused the subsequent CPUID lookup to fail when the SVSM would execute its CPUID lookup code.

igvmbuilder: fix incorrect CPUID table construction

---

kernel/src/cpu/control_regs.rs
kernel/src/cpu/efer.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/tlb.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/ptguards.rs
kernel/src/mm/vm/range.rs

VM ranges that are specific to a single CPU do not require TLB invalidations to be broadcast to multiple processors.  This is especially important during the early boot phase when no other processors are online and when the infrastructure required to broadcast TLB invalidations may not yet be fully initialized.  The same is true for temporary mappings established in a per-CPU address range.

cpu/tlb: do not broadcast per-cpu TLB flushes

---

kernel/src/igvm_params.rs

The previous IGVM memory map population code was erroneously ignoring the entry offset and writing all data into the first entry in the memory map.

igvm_params: correctly populate the memory map

---

Makefile

We run selftests with separate binaries and would like to use an upstream target to do the objcopy step.

Add a target for svsm-test.bin

---

stage1/stage1.S

The changes to support TDX from stage1 introduced an exchange of the BSP/AP index between stage1 and stage2. This was not implemented in the non-TDX case resulting in a non-zero %edi register on entry to stage2, resulting in the identity mapped page table not being configured.
This patch clears %esi on entry to stage2.

stage1: Fix boot issue where %esi was wrong on stage2 entry

---

kernel/src/mm/alloc.rs
kernel/src/mm/pagebox.rs
kernel/src/mm/validate.rs
kernel/src/svsm.rs

Add support for allocating dynamically-sized slices of values using the page allocator. This essentially works like a regular Vec, except the slice does not support resizing once created.
This is useful for the use case we have in the valid bitmap. Thus, replace the low-level page allocation calls in that code with `PageBox` uses.

mm/pagebox: add dynamically-sized slice support

---

Makefile
kernel/Cargo.toml

The svsm crate allows the libmstpm dependency to be optional, but since it's a default feature there's no actual way to use make to compile it that disables the feature. Add the necessary parts so that it can be compiled out. This allows running FEATURES='""' make to not build the mstpm.
If there's an existing or better way to do this, please let me know!

build: Allow building without mstpm

---

bootlib/src/igvm_params.rs
bootlib/src/kernel_launch.rs
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/stage2_stack.rs
igvmbuilder/src/vmsa.rs
kernel/src/boot_stage2.rs
kernel/src/config.rs
kernel/src/igvm_params.rs
kernel/src/mm/address_space.rs
kernel/src/stage2.lds
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_paging.rs
stage1/stage1.S
stage1/stage1.lds
utils/gen_meta.c

Stage2 has grown so that it cannot fit below 640 KB with enough space to provide a heap for stage2 execution.  This change relocates stage2 (and stage1 and the kernel images) up to 8 MB so that all of the memory below 640 KB can be used for the stage2 heap, and so that stage2 can continue to grow without concern for hitting any other size limits.

stage2: relocate stage2 and boot data to 8 MB

---

kernel/src/mm/pagetable.rs

Turns out that the way the iterators are implemented in RawPageTablePart::free_lvl*() the compiler makes copies of entire pages on the stack, which overflows the 32 KiB stack pretty quickly.
Iterate over references only and significantly reduce stack usage of the page-table freeing code.

kernel/mm: Reduce stack footprint of page-table freeing

---

scripts/show-stack-sizes.sh

This adds a script to find functions with excessive stack sizes.
Follow-up for https://github.com/coconut-svsm/svsm/discussions/444

scripts: add show-stack-sizes.sh

---

kernel/src/cpu/percpu.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/vm/range.rs
kernel/src/platform/snp.rs
kernel/src/sev/ghcb.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_paging.rs
kernel/src/task/tasks.rs

`get_init_pgtable_locked()` was problematic because the returned mutable reference was aliasing the mutable reference returned in `this_cpu().get_pgtable()` in stage2.
Removing `get_init_pgtable_locked()` now will probably also make it easier to implement isolated pagetables in the future because everything is already only accessing `this_cpu().get_pgtable()`.

mm: always use `this_cpu().get_pgtable()` instead of `get_init_pgtable_locked()`

---

kernel/src/requests.rs

Currently, when the guest running at VMPL2 switches back to the SVSM it is assumed that the guest VMSA virtual memory mapping is correct. However, it is possible for the VMPL2 AP to be destroyed and recreated while the AP request loop is blocked on waiting for the guest VMPL to call back to the SVSM. In this case the VMSA mapping is incorrect and the SVSM call fails.
This is fixed by updating the mappings on returning to the SVSM from the guest VMPL.

kernel/requests: Ensure guest VMSA mapping is updated on switch from VMPL2

---

fuzz/fuzz_targets/insn.rs
kernel/src/cpu/efer.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/registers.rs
kernel/src/cpu/vc.rs
kernel/src/insn_decode/decode.rs
kernel/src/insn_decode/insn.rs
kernel/src/insn_decode/mod.rs
kernel/src/insn_decode/opcode.rs
kernel/src/io.rs
kernel/src/mm/guestmem.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/ptguards.rs
kernel/src/svsm_console.rs
kernel/src/utils/util.rs

Add the instruction decoding and emulating support for ins/outs instructions. To support emulating, the InsnMachineCtx has been extended with more methods for the instruction decoder to get CPU state. And implemented these new methods for the X86ExceptionContext.
Beside provides more CPU states, it also provides the memory accessing ability to the instruction decoder via the new trait InsnMachineMem. The PageTable has been extended to support translating virtual addresses to the corresponding physical addresses, with the accessing rights been checked. And the physical addresses are temporarily mapped in the page table with contiguous virtual addresses via a PerCPUPageMappingGuard, which is wrapped in the new structure MemMappingGuard. This new structure implements the trait InsnMachineMem …

Add instruction decoding and emulating support for IOIO instructions

---

Makefile
igvmbuilder/src/cmd_options.rs
igvmbuilder/src/firmware.rs
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs

The Vanadium hypervisor is used internally by Google. It is similar to qemu in that it uses kvm.

igvm: Add the Vanadium hypervisor to igvmbuilder

---

fuzz/fuzz_targets/page_alloc.rs
kernel/src/cpu/mem.rs
kernel/src/cpu/mod.rs
kernel/src/fs/ramfs.rs
kernel/src/mm/alloc.rs
kernel/src/mm/mod.rs
kernel/src/mm/vm/mapping/rawalloc.rs

This PR fixes some soundness issues around PageRef and adds save abstractions for reading, writing, and filling a PageRef.

mm: various improvements to PageRef

---

Documentation/docs/developer/design/OBJECT.md

The syscalls design philosophy is to provide a unified interface for the user to access system resources, which are represented by object handles. This makes objects a fundamental concept in the COCONUT-SVSM kernel.
This document describes the object and object handle from both the user mode's and the COCONUT-SVSM kernel's point of view.

doc/design: Add design doc for object

---

.github/workflows/publish-docs.yml
.github/workflows/rust.yml
Documentation/docs/installation/INSTALL.md
libmstpm/Makefile
scripts/container/opensuse-rust.docker

Coconut-SVSM vendors its own copy of openssl (via git submodule), but previously it didn't pass in the right variables to libmstpm's configure script to tell it to use it. This meant that libssl-dev must be installed on the build system in order to build Coconut.
This can be bypassed by passing LIBCRYPTO_LIBS and LIBCRYPTO_CFLAGS to configure. Coconut-SVSM was previously passing in LIBCRYPTO_LIBS only, but it would double-expanding the variables meaning that it was actually passing LIBCRYPTO_LIBS="", which was not enough for configure. Fix this, and also pass LIBCRYPTO_CFLAGS so that configure realizes the libcrypto dependency is satisfied without needing it installed on the build system.
Tested by building in a docker container based on debian12 without libssl-dev.
This commit also …

tpm: Remove need for libssl build dependency

---

kernel/src/error.rs
kernel/src/syscall/mod.rs
kernel/src/syscall/obj.rs
kernel/src/task/tasks.rs
syscall/src/lib.rs
syscall/src/obj.rs

This is the code implementation for the object management. It includes 3 patches, two patches are for the COCONUT-SVSM kernel, which add the Obj trait, ObjHandle and object management. One patch is for the user mode, which add the equivalent ObjHandle define.
The implementation is made according to the object management design code, which has been reviewed at the [PR 4530](https://github.com/coconut-svsm/svsm/pull/453). Thanks to @Freax13 for the invaluable reviews!

Implement object management

---

scripts/container/build.sh
scripts/container/opensuse-rust.docker

With some recent images, the container build can fail this way if the system has incompatible packages:
Resolving package dependencies...
Problem: 1: the to be installed patterns-devel-base-devel_basis-20170319-12.5.x86_64 requires 'ncurses-devel', but this requirement cannot be provided
not installable providers: ncurses-devel-6.5.20240824-44.1.x86_64[repo-oss]
Solution 1: downgrade of libncurses6-6.5.20240922-45.1.x86_64 to libncurses6-6.5.20240824-44.1.x86_64
Solution 2: do not install patterns-devel-base-devel_basis-20170319-12.5.x86_64
Solution 3: break patterns-devel-base-devel_basis-20170319-12.5.x86_64 by ignoring some of its dependencies
Do an update before installing packages to make sure we don't have any potential conflicts, and also use `set -x` in `build.sh` to make sure …

Fix container build script

---

kernel/src/igvm_params.rs
kernel/src/platform/snp.rs
kernel/src/svsm.rs

The notion of "guest request" is specific to the SNP platform. Therefore, the global `SnpGuestRequestDriver` object should only be initialized on the SNP platform.

platform: move greq driver initialization to the SNP platform

---

Cargo.lock
kernel/Cargo.toml
kernel/src/cpu/percpu.rs
kernel/src/greq/driver.rs
kernel/src/greq/msg.rs
kernel/src/mm/page_visibility.rs
kernel/src/sev/ghcb.rs
kernel/src/sev/hv_doorbell.rs
kernel/src/stage2.rs

This PR improves the soundness of code around hypervisor-shared memory.
~The first patch, 174274d0e8ffb7757b74a42eef1082b05b8ea0a9, is blocked on https://github.com/google/zerocopy/pull/1601. Let me know if you want me to drop that patch if we don't want to wait on a new zerocopy release. I used the following patch to override zerocopy for testing:~
```diff
diff --git a/Cargo.toml b/Cargo.toml
index b7bdb46..d87444d 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -49,6 +49,9 @@ zerocopy = { version = "0.7.32", features = ["alloc", "derive"] }
packit = { git = "https://github.com/coconut-svsm/packit", version = "0.1.1" }
+[patch.crates-io]
+zerocopy = { git = "https://github.com/Freax13/zerocopy.git", rev = "68e1cc8" }
+
[workspace.lints.rust]
future_incompatible = { level = "deny", priority = …
```

soundness improvements around hypervisor-shared memory

---

kernel/src/cpu/irq_state.rs
kernel/src/sev/hv_doorbell.rs

Interrupts delivered via #HV are ignored when EFLAGS.IF=0.  When enabling interrupts, the #HV doorbell page must be checked for pending events that were suppressed while interrupts were disabled so that they do not remain pending indefinitely.

cpu: process pending #HV events when enabling interrupts

---

Makefile

Add a Makefile test target for the Hyper-V test-in-svsm IGVM file. Add a Makefile target to build all test IGVMs.

makefile: build Hyper-V flavor of test kernel binary

---

igvmbuilder/src/cpuid.rs

The test-in-svsm environment expects the vendor CPUID leaf (both base and extended) to be present in the table, so it must be included in the list specified in the IGVM file.

igvmbuilder: include vendor CPUID leaf in IGVM CPUID table

---

kernel/src/mm/ptguards.rs
kernel/src/mm/virtualrange.rs

Introduce a new smart pointer type for virtual range allocations. The new type automatically frees the virtual range from the correct allocator on drop. This significantly simplifies the logic for the     `PerCPUPageMappingGuard` methods.

mm/virtualrange: introduce the `VRangeAlloc` type

---

kernel/src/boot_stage2.rs
kernel/src/cpu/efer.rs
kernel/src/cpu/features.rs
kernel/src/igvm_params.rs
kernel/src/mm/address_space.rs
kernel/src/mm/page_visibility.rs
kernel/src/mm/pagetable.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/svsm_paging.rs

SNP validates pages by virtual address while TDX validates pages by physical address.  This PR makes it possible for code to request validation changes based on either.  This ensures that virtual mappings are not created unnecessarily on platforms that do not require them, and ensures that it can be possible to correctly obtain the physical address for validation in those cases where the caller has only a virtual address.

platform: extend the way pages are identified for validation/invalidation

---

Cargo.lock
Cargo.toml
bootlib/src/igvm_params.rs
bootlib/src/kernel_launch.rs
cpuarch/Cargo.toml
cpuarch/src/vmsa.rs
igvmbuilder/Cargo.toml
igvmbuilder/src/cpuid.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/igvm_firmware.rs
igvmbuilder/src/stage2_stack.rs
igvmbuilder/src/vmsa.rs
igvmmeasure/Cargo.toml
igvmmeasure/src/id_block.rs
igvmmeasure/src/igvm_measure.rs
igvmmeasure/src/main.rs
igvmmeasure/src/page_info.rs
kernel/src/greq/driver.rs
kernel/src/greq/msg.rs
kernel/src/mm/page_visibility.rs
kernel/src/mm/pagebox.rs
kernel/src/sev/ghcb.rs
kernel/src/sev/vmsa.rs

The new version allows us to get rid of even more unsafe code :)
~This patch was split out from #451.
This PR is blocked on a new [zerocopy release](https://github.com/google/zerocopy/pull/1604).~

update to zerocopy 0.8

---

kernel/src/cpu/idt/entry.S
kernel/src/cpu/percpu.rs

This PR contains some fixes for the #HV handler.
There's still one remaining problem which is that the `IF` flag is never ever enabled (except in some tests) and so some parts of the #HV handler are effectively dead code. The reason for that is that `irqs_disable` remembers the state of the `IF` when it's called, and if the `IF` flag is not set, `irqs_enable` will not set `IF`. This doesn't seem like intended behavior, but I'm unsure where the best place to set the `IF` flag would be.
Cc @msft-jlange Could you please test these changes in your environment that has restricted injection support?

some fixes for the #HV handler

---

Makefile
igvmbuilder/src/cmd_options.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/stage2_stack.rs
igvmbuilder/src/vmsa.rs

This change enables building an IGVM file that support the `VSM_ISOLATION` platform type.

igmvbuilder: support VSM isolation platform type

---

kernel/Cargo.toml
kernel/src/cpu/control_regs.rs
kernel/src/cpu/features.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/mod.rs
kernel/src/cpu/x86/mod.rs
kernel/src/cpu/x86/smap.S
kernel/src/cpu/x86/smap.rs

Enabling SMEP and SMAP if supported by the CPU.
To enable these, `smep` and `smap` features have to be specifically enabled, but this could be changed in the future since I think all modern CPUs support SMEP and SMAP.
I stole the way to give the CFG_SMAP bool to assembly from #455. This will likely cause a small conflict in  `kernel/src/cpu/idt/svsm.rs:265` when one of the two PR is merged.
This also conflict with the userspace PR since SMAP has to be temporary disabled to fetch user-provided pointers in syscalls arguments.
Finally, SMAP requires RFLAGS.AC to be unset to be enabled so I added a `clac` instruction in different entries, including #HV entry for which I don't really know if this is required, and if this could break something in the future. @msft-jlange could you please take a …

Enabling SMEP and SMAP

---

cpuarch/src/vmsa.rs

Previously, it was possible for a guest to exit with an exit code undefined in the GuestVMExit enum, leading to undefined behavior.
As suggested by @Freax13 in #359, we can replace this by a tuple struct, allowing unknown values.

cpuarch/vmsa: fix soundness issue with GuestVMExit

---

igvmbuilder/src/main.rs
igvmmeasure/src/main.rs

igvmbuilder and igvmmeasure are both userspace applications that do not deal with low level details like the SVSM kernel. Thus, there is no reason to allow unsafe code in them. Add a lint to prevent future additions of unsafe code.

igvmbuilder, igvmmeasure: forbid unsafe code

---

kernel/src/cpu/smp.rs
kernel/src/platform/snp.rs

The process of cloning page tables to create the page table hierarchy for a new processor does not include platform-specific logic.  Therefore it should not be implemented in the platform object.

platform: move AP page table construction into common code

---

kernel/src/cpu/smp.rs
kernel/src/platform/snp.rs

Initialization of the #HV doorbell page is a platform-specific operation.  Initialization on the BSP was already in the platform abstraction; initialization on APs should also be in the platform abstraction.

platform: move AP #HV doorbell initialization to platform

---

scripts/launch_guest.sh

The script runs with `set -e`, so if QEMU fails, we never restore Ctrl-C remapping to Ctrl-].
For example, this happens all the time when we run `scripts/test-in-svsm.sh` because QEMU exits with a value other than 0 (perhaps due to exit via isa-debug-exit).
To solve it, set a handler to re-install them when the script exits, also save the original values to restore exactly the initial configuration.

scripts/launch_guest.sh: fix restoring of terminal settings

---

.github/workflows/rust.yml

A recent PR updated Cargo.toml, but not Cargo.lock. This wasn't caught until after the PR was merged. Add a CI step to check that Cargo.lock is up to date.
Follow-up for #495

ci: check that Cargo.lock is up to date

---

kernel/src/acpi/tables.rs
kernel/src/fw_cfg.rs
kernel/src/fw_meta.rs
kernel/src/greq/pld_report.rs
kernel/src/greq/services.rs
kernel/src/mm/pagebox.rs
kernel/src/string.rs

This PR get's rid of some unnecessary uses of unsafe mainly by switching to safe alternatives provided by the zerocopy crate.

get rid of unnecessary uses of unsafe

---

kernel/src/sev/ghcb.rs
kernel/src/sev/mod.rs
kernel/src/sev/status.rs

The use of the SNP platform assumes that SEV-ES and SEV-SNP are always enabled (this is enforced during SEV status register checks).  There is no longer any reason to make decisions at runtime based on whether ES or SNP is available.

sev: remove SNP/ES checks

---

bootlib/src/platform.rs
kernel/src/platform/mod.rs
kernel/src/platform/tdp.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

Not all platforms support HLT as a way to halt execution, and therefore the panic halt must be performed through a platform-specific routine. However, at the time of a panic, the global platform object may not yet be initialized.  Instead, use a more primitive mechanism for choosing a platform-specific halt routine during panic.

panic: use a platform-specific halt routine

---

kernel/src/cpu/apic.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/igvm_params.rs
kernel/src/mm/page_visibility.rs
kernel/src/platform/mod.rs
kernel/src/protocols/apic.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/testing.rs

This has the advantage that Rust will be able to auto-deref the SvsmPlatformCell into dyn SvsmPlatform, so we don't have to explicitly call as_dyn_ref.

platform: implement Deref{Mut} for SvsmPlatformCell

---

kernel/src/error.rs
kernel/src/mm/guestmem.rs
syscall/src/call.rs
syscall/src/lib.rs
syscall/src/numbers.rs

As suggested by @Freax13, introduce a `UserPtr` wrapper around `GuestPtr` to ensure 
- No invalid memory access is done.
- Validate the address passed from the userspace to make sure it isn't pointing to kernel memory.
This PR is next in series of PRs to add initial userspace support in SVSM. This is based on PR https://github.com/coconut-svsm/svsm/pull/502

Introduce UserPtr wrapper around GuestPtr

---

kernel/src/error.rs
syscall/src/call.rs
syscall/src/lib.rs

This PR introduces a syscall implementation that provides an interface between userspace and the kernel. Additionally, it adds syscall error codes following the syscall specification [[1]].
This is the first in a series of PRs to add initial userspace support in SVSM.
[1]: https://mail.8bytes.org/pipermail/svsm-devel/2024-June/000334.html

Introduce Syscall Interface and Error Codes

---

Makefile
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/vmsa.rs

Google's Vanadium hypervisor configures certain registers to have certain values different from KVM's defaults. These shouldn't affect execution, but they need to match in order for the launch measurement to be correct.

igvmbuilder: Use Vanadium's register values when building an IGVM for vanadium

---

kernel/Cargo.toml
kernel/src/address.rs
kernel/src/cpu/extable.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/isst.rs
kernel/src/cpu/mod.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/shadow_stack.rs
kernel/src/cpu/vc.rs
kernel/src/cpu/vmsa.rs
kernel/src/mm/address_space.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/vm/mapping/mod.rs
kernel/src/mm/vm/mapping/shadow_stack.rs
kernel/src/mm/vm/mapping/vmalloc.rs
kernel/src/mm/vm/mod.rs
kernel/src/svsm.rs
kernel/src/task/schedule.rs
kernel/src/task/tasks.rs

This PR implements shadow stacks.
Shadow stacks are enabled/disabled at compile time. AFAIK all processors supporting either AMD SEV-SNP or Intel TDX support shadow stacks, so no runtime checks are implemented. This also avoids the pitfall where the hypervisor lies about shadow stack availability to maliciously lower the security of the SVSM. 
KVM intercepts accesses to the MSRs used for shadow stacks, so some host-side [modifications](https://github.com/user-attachments/files/16982253/kvm-shstk.zip) are required to make this work.
I implemented a #CP exception handler to display diagnostic information when a shadow stack-related issue occurs. We might want to disable this exception handler for release builds and cause a triple fault instead. #CP exceptions are likely a sign of something …

implement shadow stacks

---

kernel/src/cpu/idt/svsm.rs
kernel/src/syscall/class0.rs
kernel/src/syscall/obj.rs
syscall/src/class0.rs
syscall/src/def.rs
syscall/src/lib.rs
syscall/src/obj.rs

This is 4th PR in the userspace series. This PR implements exit and close syscalls.

Userspace support: Introduce exit and close syscalls

---

igvmbuilder/src/cpuid.rs
kernel/src/cpu/sse.rs

A recent change to the SVSM kernel requires XCR0 to match the value `1` when looking for CPUID[EAX=0Dh] leaves.  However, the IGVM file builder was populating the CPUID template with XCR0=0, resulting in a mismatch when the CPUID lookup was attempted.  This change sets XCR0=1 for the extended leaves in the CPUID template in the IGVM file so the constructed table matches the expected value at lookup time.

igvmbuilder: configure XCR0 as expected in CPUID tables

---

kernel/src/mm/pagetable.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/sev/utils.rs

Validating pages by virtual address may encounter a large span that is backed by 4 KB pages instead of 2 MB pages.  If a span is mapped by 4 KB pages, it must always be validated as 4 KB pages regardless of the size and alignment of the virtual address range.

platform: fix page validation issues

---

.github/workflows/rust.yml
.gitmodules
Cargo.lock
Cargo.toml
Makefile

Instead of fetching PackIt as an external modules, include it into the repository as a git submodule. This will make it easier to integrate the packit command line utility into the build process.

Use Packit as a git submodule

---

Cargo.toml
fuzz/fuzz_targets/alloc.rs
fuzz/fuzz_targets/page_alloc.rs
kernel/src/address.rs
kernel/src/cpu/gdt.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/sse.rs
kernel/src/insn_decode/insn.rs
kernel/src/mm/alloc.rs
kernel/src/mm/guestmem.rs
kernel/src/mm/pagebox.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/ptguards.rs
kernel/src/sev/utils.rs
kernel/src/stage2.rs
kernel/src/task/schedule.rs
kernel/src/tdx/tdcall.rs
kernel/src/utils/immut_after_init.rs
syscall/src/call.rs

It is good to mark functions as `unsafe` when the safety of their behavior is not guaranteed.  It is not goot to permit these functions to perform additional unsafe operations without warning.  All uses of unsafe code should require explicit `unsafe` annotation regardless of whether they appear in safe or unsafe functions.

workspace: enable `unsafe_op_in_unsafe_fn` lint

---

kernel/src/cpu/idt/svsm.rs
kernel/src/fs/api.rs
kernel/src/fs/filesystem.rs
kernel/src/fs/mod.rs
kernel/src/fs/obj.rs
kernel/src/string.rs
kernel/src/syscall/class1.rs
kernel/src/syscall/mod.rs
kernel/src/syscall/obj.rs
syscall/src/class1.rs
syscall/src/def.rs
syscall/src/lib.rs
syscall/src/obj.rs

This is 5th PR in the userspace series. This PR implements support for `OPENDIR` and `READDIR` syscalls.

Userspace support: Implement opendir and readdir syscalls

---

kernel/src/cpu/sse.rs

Hosts may choose to suppress the availablity of extended SSE state.  This should not prevent the SVSM from running, as it should be able to adapt to the SSE feature set that is available.

cpu/sse: Make use of extended SSE optional

---

kernel/src/cpu/percpu.rs
kernel/src/cpu/shadow_stack.rs
kernel/src/cpu/smp.rs
kernel/src/cpu/vmsa.rs
kernel/src/svsm.rs

The method of configuring SSP/MSR_S_CET via the VMSA only works on SNP and is not applicable to any other platform.  Enabling CET and configuring the shadow stack on the target processor is a technique that will work correctly on all platforms.

svsm: Enable CET on the target processor

---

.gitignore
kernel/src/mm/alloc.rs

Fix two unrelated issues, partially introduced my recent merges:
* Make git ignore `verus*.log` files.
* Silence warning when running `make test`.

Fix two minor issues.

---

kernel/src/mm/pagetable.rs
kernel/src/tdx/error.rs
kernel/src/tdx/tdcall.rs

- Fix the definition of TdxError::PageAlreadyAccepted
- Handle TDX_OPERAND_BUSY in TDG.MEM.PAGE.ACCEPT
- Do sanity checks on status codes

kernel/tdx: Fix TDX error codes

---

kernel/src/cpu/gdt.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/vc.rs
kernel/src/locking/rwlock.rs
kernel/src/locking/spinlock.rs
kernel/src/sev/ghcb.rs
kernel/src/sev/msr_protocol.rs
kernel/src/sev/utils.rs
kernel/src/stage2.rs

Rust defines safety specifically with respect to memory guarantees enforced by the language (ownership, typing, bound, etc.) and specifically excludes overall program correctness (including data races and deadlock).  Functions that are safe with respect to the language definition of "safe" should not be declared `unsafe`.

kernel: remove unnecessary `unsafe`

---

Documentation/docs/installation/BUILD_RECIPES.md
Documentation/docs/installation/INSTALL.md
Documentation/mkdocs.yml
build
configs/all-targets.json
configs/hyperv-target.json
configs/qemu-target.json
configs/vanadium-target.json
scripts/build.py

Add a Python script which loads build recipes from JSON files, builds COCONUT and packages it into an IGVM file.
This script is the foundation for building user-space components and package them up into a file-system image during the build process.
**Update**: With the latest version the build script supports generating multiple IGVM files with one recipe. The use-case is mostly compile-testing, as per-target firmware files are not supported.
Closes: #65

Add a rudimentary build system script

---

.github/workflows/rust.yml

This is to prevent undocumented unsafe blocks from growing before we
add comments for all of them and manage to enable
`clippy::undocumented_unsafe_blocks` lint.
Progress documented at https://github.com/coconut-svsm/svsm/issues/228.
When we fix that issue, we may remove this pipeline.
~NOTE: the second patch it's just to test the new pipeline, I'll remove it if we want to merge this PR.~
I removed that patch, you can check the behavior with a new undocumented unsafe block in https://github.com/stefano-garzarella/svsm/pull/4

CI: check new undocumented unsafe blocks

---

Makefile
configs/all-targets.json
configs/hyperv-target.json
kernel/src/address.rs
kernel/src/cpu/gdt.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/cpu/vmsa.rs
kernel/src/error.rs
kernel/src/hyperv/hv.rs
kernel/src/hyperv/mod.rs
kernel/src/hyperv/msr.rs
kernel/src/lib.rs
kernel/src/mm/address_space.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/types.rs

Hyper-V exposes a set of virtual CPUID leaves, MSRs, and a set of hypercalls to assist with virtualization.  The `hyperv` module includes definitions that permit the use of interfaces specific to Hyper-V.

hyperv: add logic specific to the use of the Hyper-V hypervisor

---

.github/workflows/rust.yml

Print more information on how to locally replicate the warnings. Also add a diff between the two `clippy` outputs (on the base branch and on the PR) to better identify the new undocumented unsafe blocks in the PR that cause the new warnings.
Run `clippy` with `--quiet` to have a cleaner diff between the two runs.
I opened a PR with an undocumented unsafe block on my fork: https://github.com/stefano-garzarella/svsm/pull/5
The output on the failing job is something like this:
```
Undocumented unsafe code blocks [PR: 224 base: 223]
ERROR: 1 new undocumented unsafe code blocks detected in this PR
enabling the clippy::undocumented_unsafe_blocks lint in this way:
$ cargo clippy --workspace --all-features --exclude packit --exclude svsm-fuzz \
--exclude igvmbuilder --exclude igvmmeasure -- -W …
```

CI: be more verbose with new undocumented unsafe blocks

---

kernel/src/cpu/percpu.rs
kernel/src/hyperv/hv.rs

The `SAFETY` comments were incorrectly formatted and unrecognized by clippy.

hyperv: fix safety comments

---

kernel/src/mm/address_space.rs
kernel/src/mm/global_memory.rs
kernel/src/mm/mod.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/ptguards.rs
kernel/src/svsm_paging.rs

This PR implements a simple API to create global mappings of physical addresses and to manage their life-times.
The implementation is temporary and includes some code duplication with the existing page-table guard implementation. This is intentional as global mappings will be re-implemented using the VM code once the global part of the COCONUT address space is managed by a `VMR` struct. Therefore no time was spent making the existing guards more generic.

Add API to manage global mappings

---

kernel/src/cpu/control_regs.rs
kernel/src/cpu/cpuid.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/mem.rs
kernel/src/cpu/msr.rs
kernel/src/cpu/shadow_stack.rs
kernel/src/cpu/sse.rs
kernel/src/cpu/tlb.rs

Add safety comments for the inline assembly blocks.
This is part of the effort to resolve https://github.com/coconut-svsm/svsm/issues/228 and enable `undocumented_unsafe_blocks` clippy lint.

kernel/cpu: add safety comments

---

kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/percpu.rs
kernel/src/sev/hv_doorbell.rs

Exception handlers (other than IST-based exceptions) should run with interrupts enabled if interrupts were enabled at the time the exception was raised.  This is necessary to ensure that the `IrqState` nesting management is not confused by nesting that might occur within an exception handler.  In addition, most exceptions can safely tolerate interrupts, and need not impact system stability by suppressing interrupt delivery (this is particularly true for #VC exceptions, which can take a long time to execute due to emulation in the host).
IST-based exceptions must keep interrupts disabled as long as they execute on the IST stack (this currently applies only to #DF, which is fatal anyway).
Interrupt handlers must run with interrupts disabled, but need to update the `IrqState` in case they …

cpu/idt: Handle interrupt nesting correctly

---

kernel/src/cpu/percpu.rs
kernel/src/cpu/tss.rs
kernel/src/task/schedule.rs

The only fields of the TSS that ever require modification are the IST fields and RSP0.  Since RSP0 has to be modified on every task switch, it is undesirable to store TSS in a `Cell` because that requires copying the entire TSS in and out of the cell in order to modify just the single field.  Instead, the TSS can be made immutable, and can implement interior mutability for its own fields.  However, `Cell` cannot be used directly in this case because the X86 architecture defines the TSS such that the stack pointers are unaligned, and therefore assembly has to be used to modify the fields.

cpu: implement interior mutability in `X86Tss`

---

kernel/src/svsm_paging.rs

Init page table is loaded twice, in the end of `init_page_table()` and just after in `svsm_start()`. We can remove the first one.

kernel/pagetable: remove duplicate page table load

---

kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/percpu.rs
kernel/src/sev/hv_doorbell.rs

This reverts commits 23ff1bf383974ff457ae9f3d6adf2c25a9fabb84 and 20fecdccfd86b75a950d7eb2a7298556f3a583ce.
The original commit broke user-space support in some weird ways. Revert it until things have been sorted out.

Revert "cpu/idt: Handle interrupt nesting correctly"

---

kernel/src/cpu/irq_state.rs
kernel/src/task/tasks.rs

Prefer use of symbolic constants instead of numeric values for clarity.

task: use a symbolic constant to represent EFLAGS.IF

---

Makefile

A recent merge broke indentation in the Makefile, making CI fail. Fix that.

Makefile: Fix indendation

---

kernel/src/cpu/control_regs.rs
kernel/src/mm/alloc.rs
kernel/src/platform/snp_fw.rs
kernel/src/protocols/core.rs
kernel/src/svsm.rs
kernel/src/utils/util.rs

- As described in #359, `zero_mem_region()` should be unsafe.
- Writing to control registers can violate memory safety, therefore functions writing to CR0, CR3 and CR4 should also be unsafe. This led to making `flush_tlb_global_percpu()` unsafe too. Since I don't know perfectly the TLB code, maybe it's not necessary. Comments are very welcome here. Also, if it's correct to make `flush_tlb_global_percpu()` unsafe, for consistency reason I guess we should put other TLB helpers unsafe (again, comments are welcome here).
- Inlining control regs helpers

Making zero_mem_region() and control regs helpers unsafe

---

kernel/src/cpu/apic.rs
kernel/src/platform/tdp.rs
kernel/src/sev/hv_doorbell.rs
kernel/src/tdx/tdcall.rs

This PR adds additional missing safety comments to describe `unsafe` blocks.

kernel: add additional safety comments

---

kernel/src/cpu/gdt.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/mod.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/vmsa.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

Configuring TSS on the current CPU requires a valid GDT entry, but the GDT entry only needs to valid long enough to execute the LTR instruction.  Modifying the global GDT for this purpose is undesirable, even if safety is guaranteed by wrapping the global GDT with a lock.  It is more straightforward to keep the global GDT constant, and to create a temporary writable GDT on each processor to use long enough to execute LTR and configure the TSS.

cpu: use temporary GDT structures to load TSS

---

Cargo.lock
fuzz/fuzz_targets/fs.rs
kernel/src/cpu/idt/svsm.rs
kernel/src/error.rs
kernel/src/fs/api.rs
kernel/src/fs/buffer.rs
kernel/src/fs/filesystem.rs
kernel/src/fs/mod.rs
kernel/src/fs/obj.rs
kernel/src/fs/ramfs.rs
kernel/src/mm/alloc.rs
kernel/src/mm/guestmem.rs
kernel/src/mm/mod.rs
kernel/src/mm/vm/mapping/file_mapping.rs
kernel/src/syscall/class1.rs
kernel/src/task/exec.rs
syscall/Cargo.toml
syscall/src/call.rs
syscall/src/class1.rs
syscall/src/def.rs

Here is an initial implementation of the remaining file-system system calls, namely:
* OPEN
* READ
* WRITE
* SEEK
* TRUNCATE
TRUNCATE was not initially specified, so READDIR and OPENDIR get new syscall numbers.
The code is completely untested and posted for reference and awareness only. I move the PR out of Draft state once I have tested all new system calls.

File System SysCalls

---

kernel/src/console.rs
kernel/src/cpu/idt/entry.S
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/fs/console.rs
kernel/src/fs/mod.rs
kernel/src/svsm.rs
kernel/src/syscall/obj.rs
kernel/src/task/exec.rs
kernel/src/task/schedule.rs
kernel/src/task/tasks.rs
syscall/src/class1.rs
syscall/src/console.rs
syscall/src/lib.rs
syscall/src/obj.rs
user/init/src/main.rs
user/lib/src/console.rs
user/lib/src/lib.rs
user/lib/src/locking.rs

This PR implements console output support for user-mode processes. In user-mode code the `print!` and `println!` macros can now be used to print messages to the SVSM console.
It depends on PRs #539 and #548 and is here for testing and initial review. ~I will keep it in draft state until the dependencies have been merged.~

User-mode console support

---

configs/hyperv-target.json

Include the Hyper-V firmware file when a pathname is specified to the build script.

build: include FW file in hyper-v configuration

---

kernel/src/platform/native.rs

Support EOI by issuing a write to the APIC EOI register.

platform: support EOI on the native platform

---

igvmbuilder/src/igvm_builder.rs

The VSM flavor of the IGVM file must specify the "VTL2 protectable" flag on the kernel memory region in order to execute correctly when running in VTL 2.

igvmbuilder: set VTL2 protection flag where required

---

Documentation/docs/installation/INSTALL.md
kernel/src/cpu/vc.rs
scripts/launch_guest.sh

Update the documentation and scripts for the new development trees for Linux and QEMU.

Dev tree update

---

kernel/src/cpu/percpu.rs

Make sure the guest OS can not access the VMSA pages of the SVSM by only giving permissions up to VMPL1.

kernel/cpu: Fix access permissions for SVSM VMSAs

---

kernel/src/svsm_paging.rs

Boot memory regions aren't always page-aligned. For example, kernel_fs_end cannot always be page-aligned because the size of the FS area has to match that of its original image exactly. Make sure the memory region always has a page-aligned size in
invalidate_boot_memory_region(). The starting address is always checked during page invalidation so just assume the caller will do the right thing.

svsm_paging: Ensure page alignment during invalidation

---

kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/mod.rs
kernel/src/cpu/percpu.rs
kernel/src/locking/common.rs
kernel/src/locking/mod.rs
kernel/src/locking/rwlock.rs
kernel/src/locking/spinlock.rs
kernel/src/sev/hv_doorbell.rs
kernel/src/task/schedule.rs
kernel/src/types.rs

Using TPR for interrupt reentrancy protection allows high-priority interrupts to be serviced while low-priority interrupts are masked.  This PR introduces TPR management logic and integrates TPR management into locking mechanisms.

kernel: use TPR for interrupt reentrancy protection

---

kernel/src/vtpm/tcgtpm/mod.rs
libtcgtpm/deps/libtcgtpm.h

`_plat__NVEnable()` and `_plat__NVDisable()` APIs were updated in the new TCG TPM reference implementation to include an additional `paramSize` parameter (size_t) in their signatures.
This patch synchronizes the header file and Rust FFI calls with the new function prototypes.
Previously, the outdated header and calls passed fewer arguments than required by the new TCG TPM library. However, this mismatch did not cause issues because the new parameter (paramSize) is not used by the new implementation.
Additionally, the first parameter of `_plat__NVDisable()` has changed from `int delete` to `void* platParameter` in the new signature. However, the actual value passed (1) remains the same.
In the future we should find a better way to keep the headers synchronized and avoid this problem. …

libtcgtpm: update _plat__NVEnable and _plat__NVDisable signatures

---

.github/workflows/rust.yml

`bindgen` is used in our build process to build libtcgtpm. CI recently started to fail because it was not installed.
Add a step to make sure `bindgen` is installed correctly in our workflows.

CI: install bindgen-cli

---

Makefile
bootlib/src/igvm_params.rs
igvmbuilder/src/igvm_builder.rs
kernel/src/config.rs
kernel/src/cpu/vc.rs
kernel/src/greq/services.rs
kernel/src/igvm_params.rs
kernel/src/lib.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/svsm.rs
kernel/src/testing.rs
kernel/src/testutils.rs

The `test-in-svsm` build configuration should support environments other than SNP running on QEMU.

testing: support configurations other than SNP/QEMU

---

kernel/src/requests.rs

If the request loop determines that there is no active VMSA, the processor enters a halt state.  This halt state can terminate if an interrupt is received.  If that happens, the request loop will observe that no change to the VMSA mapping has been requested.  In this case, the request loop must return to the halt state rather than attempting to process any requests.

requests: handle interrupts when halted in the request loop

---

igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/main.rs
igvmbuilder/src/paging.rs
igvmbuilder/src/vmsa.rs

The VSM environment requires CR0.PG to be set when entering VTL 2 for the first time.  In this environment, the IGVM file must be built with initial page tables that map the low 4 GB, which permits stage 2 to start with paging enabled.  This also requires that stage 2 must start in long mode, because the paging mode cannot be changed once the VM starts executing (if CR0.PG must always be set, then it is not possible to change from 3-level PAE tables to 4-level tables).  Stage 2 will still start executing in 32-bit mode as usual, and will rebuild the page tables in its own memory area, as it always has, but that code can now execute with paging enabled as required by VSM.

igvmbuilder: enable long mode paging in the initial VSM context

---

kernel/src/platform/native.rs

For simplicity and consistency, require the native platform to use X2APIC so that APIC management can be identical across all native environments.

platform/native: require the use of X2APIC

---

bootlib/src/kernel_launch.rs
kernel/src/cpu/apic.rs
kernel/src/cpu/cpuset.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/ipi.rs
kernel/src/cpu/mod.rs
kernel/src/cpu/percpu.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/sev/status.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/types.rs
kernel/src/utils/mod.rs
kernel/src/utils/scoped.rs

This change includes logic to support sending inter-processor interrupts (IPIs) to other processors.  An IPI can be sent as a multicast message, or as a unicast message to a specific processor as a mutable message which receives a response.  All IPI delivery is synchronous, meaning that the sender will block until the IPI is delivered and the receiver has processed it.

cpu: implement IPI support

---

fuzz/fuzz_targets/bitmap_allocator.rs
kernel/src/cpu/percpu.rs
kernel/src/mm/address_space.rs
kernel/src/mm/virtualrange.rs
kernel/src/mm/vm/range.rs
kernel/src/task/tasks.rs
kernel/src/utils/bitmap_allocator.rs

Each task uses a portion of the kernel address space to store task-specific memory, which is only visible in the context of the task that owns it.  However, references to task-specific memory can be passed between tasks, and Rust memory safety relies on the principle that any reference (which is captured by its virtual address) must refer to the same underlying data in every context in which that reference is used.  This safety principle is defeated if any address is valid in more than one task at a time.  Assigning each task a unique portion of the address space ensures that any per-task address that crosses a task boundary will cause a fault instead of referring to the wrong data.

task: assign each task a unique portion of the kernel address space

---

kernel/src/cpu/tlb.rs
kernel/src/platform/mod.rs
kernel/src/platform/snp.rs
kernel/src/sev/mod.rs
kernel/src/sev/tlb.rs
kernel/src/svsm.rs

Different platforms implement TLB flush in different ways, so TLB flush operations should be abstracted in the platform object.

platform: abstract tlb flush

---

kernel/src/mm/alloc.rs
kernel/src/vtpm/tcgtpm/mod.rs
kernel/src/vtpm/tcgtpm/wrapper.rs

This is part of the effort for #228 to enable `undocumented_unsafe_blocks` clippy lint.

vtpm: add safety comments and fix small issues

---

bootlib/src/kernel_launch.rs
igvmbuilder/src/igvm_builder.rs
igvmbuilder/src/main.rs
igvmbuilder/src/sipi.rs
kernel/src/cpu/control_regs.rs
kernel/src/cpu/efer.rs
kernel/src/cpu/idt/common.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/platform/native.rs
kernel/src/svsm.rs

Native platforms that cannot make use of the Hyper-V hypercalls require the use of INIT/SIPI to perform multi-processor startup.

platform/native: use SIPI for API startup

---

Cargo.lock
Cargo.toml
bootlib/src/igvm_params.rs
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
kernel/src/igvm_params.rs
kernel/src/stage2.rs

If the IGVM memory map contains a PARAVISOR_RESERVED entry, then place the SVSM kernel at that region instead of the region specified in the IgvmParamBlock. If no such entry exists in the memory map, then continue using the IgvmParamBlock.
This allows the hypervisor to dynamically resize the SVSM based on the machine shape without changing the IgvmParamBlock and thus the launch measurement. This is necessary because the SVSM uses more memory when there are more vCPUs (and, in the future, guest memory).
Note this relies on an unpublished IGVM spec change to add the PARAVISOR_RESERVED MemoryMapEntryType.

stage2: Use IGVM memory map to resize SVSM kernel

---

.github/workflows/rust.yml

GitHub deprecated v3 of these actions which makes CI failing. Fix it by switching to v4.

Github/workflows: Use upload/download-artifact@v4

---

kernel/src/address.rs
kernel/src/boot_stage2.rs
kernel/src/cpu/smp.rs
kernel/src/mm/vm/mapping/kernel_stack.rs
kernel/src/stage2.rs
kernel/src/svsm.rs
kernel/src/task/tasks.rs
kernel/src/utils/util.rs

The x86-64 ABI requires 16b-aligned stack frames. Stack misalignment can sometimes lead to hard-to-debug segfaults because x86-64 code that follows the calling convention can assume that stack frames are 16b-aligned. This patch series makes sure this requirement is respected at various transition points in SVSM.

Make sure stack frames are 16-byte-aligned

---

kernel/src/platform/tdp.rs

Several methods of the platform object can be implemented as no-op methods in the TDP environment because there is no required work associated with those methods.  There is no need to return an uninmplemented error.  With this change, the kernel can boot and execute the test-in-svsm environment on a single vCPU (at least in the Hyper-V configuration which suppresses certain tests).

platform/tdp: remove unnecessary `Unimplemented` errors

---

bootlib/src/kernel_launch.rs
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_firmware.rs
kernel/src/boot_stage2.rs
kernel/src/fw_cfg.rs
kernel/src/igvm_params.rs
kernel/src/mm/memory.rs
kernel/src/platform/tdp.rs
kernel/src/stage2.rs
kernel/src/svsm_paging.rs

This patch series reuses the logic introduced in https://github.com/coconut-svsm/svsm/pull/581. A software-based mailbox is used for AP signaling. TD APs will enter `ap_request_loop()` after this series is applied.

Add support for TD SMP

---

kernel/src/mm/memory.rs
kernel/src/platform/snp_fw.rs
kernel/src/stage2.rs
kernel/src/svsm_paging.rs
kernel/src/utils/memory_region.rs

MemoryRegion is often used for logging. Provide generic implementations for fmt::Display and fmt::LowerHex.

kernel/utils/memory_region: Implement formatting traits

---

.github/workflows/rust.yml
Cargo.lock
Documentation/docs/installation/INSTALL.md
libtcgtpm/Cargo.toml
libtcgtpm/Makefile
libtcgtpm/build.rs
scripts/container/opensuse-rust.docker

We had several issues in our CI because we forgot to install `bindgen-cli` used in the libtcgtpm/Makefile to generate the TPM bindings.
Instead of using `bindgen-cli` (and then having as a requirement to have it installed), let's use `bindgen` in build.rs, this way the dependency is handled directly by cargo.
Let's also clean up the references to `libtcgtpm/src/bindings.rs` since bindings were already generated in the OUT_DIR.
Remove the reference to install `bindgen-cli` in the CI workflows, Documentation, and container image.

libtcgtpm: use bindgen in build.rs instead of bindgen-cli in Makefile

---

kernel/src/cpu/smp.rs
kernel/src/svsm.rs
kernel/src/task/schedule.rs

Starting the scheduler is an unsafe operation because it relies on there not being a current task, which is a guarantee the compiler cannot make on its own.
Also, a function that returns a pointer is not necessarily unsafe.  The operation of using the pointer is where the code becomes unsafe.

task: fix some safety issues

---

.github/workflows/rust.yml

After merging https://github.com/coconut-svsm/svsm/pull/606 we don't need to install `bindgen-cli` anymore to build our code.
Depends on #606

github/workflows: remove `Install bindgen-cli` step

---

kernel/src/cpu/idt/svsm.rs

SYS_RMDIR was incorrectly handled by sys_mkdir() so fix that.

cpu/idt: Fix SYS_RMDIR

---

kernel/src/io.rs

Add safety comments for the inline assembly blocks.

kernel/io: add safety comments

---

kernel/src/sev/ghcb.rs
kernel/src/sev/secrets_page.rs
kernel/src/stage2.rs
kernel/src/task/exec.rs
kernel/src/utils/util.rs

New simple safety comments around our code. More like fixes of comments not put before the unsafe block, blocks within unsafe functions that demand the caller, FFI, inline asm, etc.

kernel: add safety comments

---

kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/platform/mod.rs
kernel/src/platform/snp.rs
kernel/src/requests.rs
kernel/src/sev/msr_protocol.rs
kernel/src/svsm.rs
kernel/src/task/mod.rs
kernel/src/task/schedule.rs
kernel/src/utils/mod.rs
kernel/src/utils/util.rs

Move the SVSM request loop out of the idle task and into a separate task, and invoke it only on SNP platforms.  This is a step towards moving SVSM request processing out of the kernel, and enabling it to be excluded in configurations that only support paravisor processing.

requests: refactor SVSM request loop

---

scripts/build.py

Exit the build python script with a non-zero code in case the build fails.
This is useful when calling it from other scripts.
Additionally include the filename of the recipe in the
error messages printed.
Currently it does this:
```
$ ./build configs/qemu-target.json; echo $?
Building igvmbuilder...
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
Building igvmmeasure...
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
Building packit...
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
Building svsm...
Compiling svsm v0.1.0 (/home/osteffen/work/svsm/coconut/svsm/kernel)
error: expected `;`, found `asdasda`
--> kernel/src/kernel_region.rs:14:45
|
14 |     MemoryRegion::from_addresses(start, end)
| …
```

build: Exit with non-zero code on failure

---

kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/x86/mod.rs
kernel/src/cpu/x86/smap.S
kernel/src/cpu/x86/smap.rs
kernel/src/crypto/mod.rs
kernel/src/crypto/rustcrypto.rs
kernel/src/greq/driver.rs
kernel/src/greq/mod.rs
kernel/src/greq/msg.rs
kernel/src/greq/pld_report.rs
kernel/src/greq/services.rs
kernel/src/vtpm/mod.rs
kernel/src/vtpm/tcgtpm/mod.rs
kernel/src/vtpm/tcgtpm/wrapper.rs
libtcgtpm/build.rs
libtcgtpm/deps/openssl_svsm.conf

Only "// Author: " is the permissible format in the pre-commit hook. Fix them so that we stop running into pre-commit errors on these existing headers.
The is a follow-up of https://github.com/coconut-svsm/svsm/pull/620#discussion_r1955801517

Documentation: Replace "Authors:" with "Author:" in headers

---

.github/workflows/rust.yml

In the `unsafe-check` job, if `cargo clippy` fails, we don't have any log since we are redirecting the stderr to a file to count the number of undocumented unsafe blocks.
We don't expect it to fail, since other steps in `check` job should check this case, but it has happened in some cases.
Print the file content in case of `cargo clippy` returns with error, so we can debug better CI failures.

github/workflows: print clippy output in case of errors

---

bootlib/src/igvm_params.rs
fuzz/fuzz_targets/acpi.rs
igvmbuilder/src/gpa_map.rs
igvmbuilder/src/igvm_builder.rs
kernel/src/acpi/tables.rs
kernel/src/config.rs
kernel/src/igvm_params.rs
kernel/src/platform/mod.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

The IGVM format specifies a mechanism for the host to inject an MADT into the guest address space.  This MADT should be used to determine the set of APIC IDs associated with the set of CPUs that will be started by the guest.

igvm: use MADT for determining APIC IDs

---

kernel/src/cpu/control_regs.rs
kernel/src/cpu/features.rs
kernel/src/cpu/gdt.rs
kernel/src/cpu/idt/common.rs

UMIP (User-Mode Instruction Prevention) prevents user-mode applications from executing SGDT/SIDT/SLDT/SMSW/STR. A `#GP(0)` is raised if any of these instrctions is executed in CPL > 0 and CR4.UMIP = 1. It is generally a good idea to enable such prevention before user space comes up because these instructions can leak critical information regarding memory layout and configuration.

Enable UMIP

---

kernel/src/cpu/x86/apic.rs
kernel/src/platform/native.rs
kernel/src/platform/tdp.rs

Cleanup the X2APIC code by moving accesses for `kernel/src/cpu/x86/apic.rs` and calling the accessors from the native and TDP platform implementations.
Also fix IRQ delivery with QEMU/KVM by setting the ASE bit in APIC.SPIV on X2APIC initialization.

Cleanup X2APIC code and fix IRQ delivery on the Native Platform with QEMU

---

kernel/src/cpu/control_regs.rs
kernel/src/cpu/shadow_stack.rs
kernel/src/platform/mod.rs
kernel/src/platform/snp.rs
kernel/src/svsm.rs

Attempting control state changes and catching related exceptions is not a terribly robust way of feature detection.  The architecturally approved mechanism for feature detection is CPUID, and in those cases where it is unavailable or unreliable due to constraints within the underlying platform, there other usually better enumeration mechanisms available.

cpu: use robust mechanisms to determine availability of CET

---

kernel/src/cpu/vc.rs
kernel/src/insn_decode/decode.rs

There is a path to emulate MMIO instructions in the IOIO #VC handler, I think that's not what we want.
**I don't have access to a SEV-SNP platform, I would need someone to test it, test-in-svsm included. Thanks!**

kernel/vc: remove MMIO handling from IOIO VC

---

igvmbuilder/src/ovmf_firmware.rs

Make the kernel hashes memory area of OVMF as prevalidated. This makes
it accessible by the firmware and thus the kernel hashes feature usable.
The AmdSev variant of OVMF for example relies on this area to be
readable.

igvmbuilder: prevalidate kernel hashes area

---

kernel/src/cpu/smp.rs
kernel/src/platform/tdp.rs

The TDX module does not permit EFER to be reloaded when running in an L1, so skip the reload of EFER during the AP startup flow when running under TDX.

tdp: do not load EFER during AP startup

---

kernel/src/task/tasks.rs

Each TaskVirtualRegionGuard gets a unique index that indicates where its vaddr region is. Previously only even indices were allocated since the alloc function was given an alignment of 1, but this is unncessary as every index is valid.
This doubles the number of possible tasks from 512 to 1024. By default, 3 tasks are created per vCPU, so this doubles the number of vCPUs supported from 170 to 341 (in theory). Actually tested with 224 vCPUs.

task: Remove alignment requirement for TaskVirtualRegionGuard indices

---

kernel/src/cpu/idt/svsm.rs
kernel/src/platform/capabilities.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/svsm.rs
kernel/src/syscall/class3.rs
kernel/src/syscall/mod.rs
kernel/src/tdx/error.rs
kernel/src/tdx/tdcall.rs
syscall/src/class3.rs
syscall/src/def.rs
syscall/src/lib.rs

The `CAPABILITIES` syscall takes an index as its input and returns the corresponding capability in a u64 as per the syscall ABI.
Bits [2:0] of GlobalFeatureFlags are defined as the platform type.

syscall: Implement CAPABILITIES

---

kernel/src/cpu/percpu.rs
kernel/src/mm/guestmem.rs
kernel/src/mm/memory.rs
kernel/src/mm/ptguards.rs

With arbitrary length memory access in service requests, we need to be able to read/write memory across multiple pages safely.
This is groundwork for the attestation service to write manifests and read "selectors" of arbitrary length.

Add safe memory constructs for large requests 

---

kernel/src/cpu/extable.rs
kernel/src/cpu/idt/entry.S
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/percpu.rs
kernel/src/debug/stacktrace.rs
kernel/src/stage2.rs
kernel/src/svsm.lds
kernel/src/svsm.rs

Allow the stack unwinder to work right after preparing the console in the SVSM kernel. Use an early #PF handler and the early exception table to determine if the PerCpu page is ready. If there is no PerCpu available, perform best-effort unwinding based on the default stack regions.

Allow early stack unwinding

---

kernel/src/platform/mod.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

All callers of `SVSM_PLATFORM` expect to call through a dynamic `SvsmPlatform` trait reference.  For efficiency, the dynamic trait reference should be stored in the global.  This is better than storing a cell containing an enum which must be matched every time the static platform is referenced.

platform: make `SVSM_PLATFORM` a dynamic reference

---

scripts/launch_guest.sh

Add the `-nocc` option to the Qemu launcher script to use the "native
mode", aka run on regular hardware without memory encryption.

scripts/launch_guest.sh: add option to launch in native mode

---

kernel/src/cpu/ipi.rs
kernel/src/cpu/irq_state.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/platform/snp.rs
kernel/src/requests.rs
kernel/src/sev/snp_apic.rs

Until KVM supports separate interrupts per privilege context (VMPL, TDP L2, etc.), interrupt state must be exclusively associated with the guest OS, not with the SVSM.  However, prior to the guest being started on any processor, there is no reason not to make use of interrupts in the SVSM because there is no ambiguity.  This change permits the use of IPIs up to the point in time that all processors are ready to begin the request loop on all CPUs, at which point IPI usage is suppressed and interrupt state becomes exclusive to the guest OS.

kernel: permit the use of IPIs prior to guest entry

---

kernel/src/cpu/apic.rs
kernel/src/cpu/ipi.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

The `PERCPU_AREAS` structure is not multi-thread safe because it contains a `Vec` that is modified as additional CPUs are started.  This would be safe when executing in a single-processor environment, but as each processor is started, additional CPU state is pushed onto `PERCPU_AREAS`, causing it to continue to change even after other processors have started running.  In order for `PERCPU_AREAS` to be sound, it must be fully populated before any additional processor can begin running.

cpu: resolve safety issues with `PERCPU_AREAS`

---

kernel/src/cpu/cpuid.rs
kernel/src/cpu/features.rs
kernel/src/hyperv/hv.rs
kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/sev/ghcb.rs

RCX must always be supplied when sending a GHCB CPUID NAE event to the hypervisor. When RCX is not supplied, the GHCB call will (or should) fail. The KVM hypervisor will log the following:
kvm_amd: kvm [15381]: vcpu0, guest rIP: 0x0 vmgexit: exit code 0x72 input is not valid
Update the GHCB cpuid() function to supply RCX with a value of zero.

kernel/sev/ghcb: Always supply RCX on GHCB CPUID NAE event

---

kernel/src/cpu/msr.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/x86/apic.rs
kernel/src/cpu/x86/x2apic.rs
kernel/src/platform/tdp.rs
kernel/src/tdx/apic.rs
kernel/src/tdx/mod.rs

TDX guests rely on virtual x2APIC mode + host VMM APIC emulation for APIC functionalities. Reuse the APIC driver implementation and catch x2APIC MSR access #VEs as they appear.

platform/tdp: Add IPI support

---

.github/workflows/rust.yml
elf/src/load_segments.rs
igvmbuilder/src/igvm_firmware.rs
kernel/Cargo.toml
kernel/src/cpu/ipi.rs
kernel/src/debug/gdbstub.rs
kernel/src/mm/alloc.rs
kernel/src/mm/vm/mapping/api.rs
kernel/src/utils/immut_after_init.rs
rust-toolchain.toml
user/init/Cargo.toml
user/lib/src/lib.rs

This improves address provenance hygiene to keep exposed addresses as close to their use as can be managed.
Suggested-by: Adam Dunlap <acdunlap@google.com>

Update to 1.84.1 for strict_provenance use in copy_bytes

---

kernel/src/cpu/ipi.rs
kernel/src/cpu/percpu.rs
kernel/src/cpu/smp.rs
kernel/src/hyperv/hv.rs
kernel/src/mm/virtualrange.rs
kernel/src/platform/tdp.rs
kernel/src/requests.rs
kernel/src/svsm.rs
kernel/src/task/mod.rs
kernel/src/task/schedule.rs
kernel/src/task/tasks.rs

This change modifies the request processing loop startup process to create a single request processing task (when the configuration requires it), and that single task starts all other request processing tasks, with affinity to each vCPU as necessary.  This models the behavior that will be used when request processing is moved out of the kernel and into a user-mode process.

request: create all request processing tasks from the primary loop

---

scripts/build.py
user/init/Cargo.toml

With newer versions of the Rust toolchain cargo started to rename the user-mode output binaries, which broke the build for the SVSM file-system image.
Fix that by honouring the 'output_file' parameter for cargo recipes and specifying an alternative build output name for userinit.

build: Honour 'output_file' for cargo builds

---

kernel/src/boot_stage2.rs
kernel/src/stage2.lds

Apparently the Rust compiler decided to include some code into the stage2 binary which references symbols which are only present in the SVSM. This is not the first time this happened and currently it can be seen in release builds.
This PR works around this by providing some of the SVSM symbols as dummies in the stage2 binary as well. This fixes the linker issue and makes the build more robust for now.
The longer term solution still needs to be splitting out Stage2 into a separate Rust crate to better manage the code sharing between SVSM and Stage2.

Work around build failures in release builds

---

.github/workflows/rust.yml

Failures of the nightly toolchain provide useful information about keeping the build healthy, but those failures should not block PRs from merging.

CI: treat nightly failures as warnings

---

.github/workflows/rust.yml

We have a pipeline with nightly toolchain to check the formatting of documentation, but lately the CI fails and it seems we were running `cargo fmt` on the stable toolchain.
Let's explicate the use of the nightly toolchain.

github/workflows: use nightly toolchain for "Format doctests"

---

kernel/src/block/virtio_blk.rs

Hyper-V doesn't support virtio-blk, so the virtio-blk tests should not be run on that platform.

block: suppress virtio tests on hyper-v

---

kernel/src/mm/guestmem.rs

The request to use pointers more explicitly instead of `as u64` came from @AdamCDunlap. This is a type safety enhancement.

Use strict_provenance for copy_bytes

---

.github/workflows/rust.yml
libtcgtpm/Makefile
libtcgtpm/deps/libcrt/include/libcrt.h
libtcgtpm/deps/libcrt/src/stub.c
libtcgtpm/deps/openssl_svsm.conf

Policies in certain environments might prohibit the use of OpenSSL 1.x, which is currently used for the vTPM.
This PR switches over to OpenSSL 3.4.1.
Many thanks to @cclaudio for digging up his old branch for me which enables OpenSSL 3.1.
Unfortunately, this change results in a larger SVSM binary, not sure if this is a problem.
Adding `-ffunction-sections` and `-fdata-sections` to the OpenSSL build config, as well as disabling the `dh` feature, reduces the size again somewhat.
Here is a comparison of the sizes of the build for QEMU:
|               |  Size (bytes) |        | 
| :------------ |          ---: |    --- |
| openssl 1.1.1 |       5669136 |   +0%  |
| openssl 3.1.4 |       6614448 | +16.7% |
| openssl 3.4.1 |       6849712 | +20.8% |
| openssl 3.4.1 (gcc opts) |       6247024 | …

libtcgtpm: Switch to OpenSSL 3

---

.github/workflows/rust.yml

In the `unsafe-check` pipeline we need to build both the current PR branch and the base branch to compare the number of unsafe blocks. If the PR changes the toolchain, the step where we run `clippy` on the base branch fails, because we haven`t installed it.
Install the toolchain and components for the base branch as well just after checkout to avoid this problem.

github/workflows: install toolchain and components for the base branch

---

kernel/Cargo.toml
kernel/src/cpu/cpuset.rs
kernel/src/cpu/tss.rs
kernel/src/crypto/mod.rs
kernel/src/fs/filesystem.rs
kernel/src/greq/driver.rs
kernel/src/greq/msg.rs
kernel/src/greq/services.rs
kernel/src/mm/alloc.rs
kernel/src/mm/vm/mapping/api.rs
kernel/src/mm/vm/mapping/file_mapping.rs
kernel/src/mm/vm/mapping/kernel_stack.rs
kernel/src/mm/vm/mapping/rawalloc.rs
kernel/src/mm/vm/range.rs
kernel/src/protocols/vtpm.rs
kernel/src/task/schedule.rs
kernel/src/utils/immut_after_init.rs
kernel/src/vtpm/mod.rs
kernel/src/vtpm/tcgtpm/tss.rs
rust-toolchain.toml
stage1/Cargo.toml
user/lib/src/locking.rs

As discussed before, the attestation proxy in #528 will rely on [cocoon-tpm](https://github.com/nicstange/cocoon-tpm)'s crypto crate for generating EC keys required for attestation. This crate depends on the 1.86 toolchain. Bump the toolchain version to accommodate this.

toolchain, kernel, stage2: Bump rust version to 1.86.0

---

Cargo.lock
bootlib/Cargo.toml
bootlib/src/firmware.rs
bootlib/src/lib.rs
igvmbuilder/src/ovmf_firmware.rs
kernel/src/platform/snp_fw.rs
kernel/src/utils/fw_meta.rs

Since the uuid crate is already being used in the SVSM kernel and other packages in the workspace, rely on it instead of the in-kernel implementation. While we are at it, centralize GUIDs into the bootlib crate, so that the kernel and igvmbuilder can access the same definitions.

kernel: remove manual UUID implementation

---

Documentation/docs/developer/CONTRIBUTING.md
Documentation/docs/index.md
README.md

We are shutting down the old mailing list, update all references to the mailing list in our documentation.

Documentation: update the mailing list address

---

Makefile

Doctests do not work with custom test frameworks, so they cannot be included in the test_in_svsm build. See
https://github.com/coconut-svsm/svsm/issues/705 for more details.

build: Remove doctests from test_in_svsm

---

kernel/src/protocols/vtpm.rs
kernel/src/vtpm/mod.rs
kernel/src/vtpm/tcgtpm/mod.rs
kernel/src/vtpm/tcgtpm/tss.rs

Creating a mutable reference to the guest buffer, could have been an UB because the guest could potentially modify it.
So, let's copy the guest buffer to an internal one and then copy it back to give the result to the guest. To avoid overflowing the stack, allocate the buffer with Vec.

kernel/vtpm: fix potential UB when accessing guest buffer

---

kernel/src/cpu/percpu.rs
kernel/src/greq/msg.rs
kernel/src/mm/page_visibility.rs
kernel/src/sev/hv_doorbell.rs

* Fix `SharedBox` trait bounds so that methods are truly safe
* Attempt to restore page visibility on failure during `SharedBox::try_new_zeroed()`.
* Remove the last user of the low level `make_page_shared()` and `make_page_private()` functions, and then make them private to the `page_visibility` module.

mm/page_visibility: `SharedBox` improvements

---

kernel/src/cpu/percpu.rs
kernel/src/hyperv/hv.rs
kernel/src/hyperv/mod.rs
kernel/src/mm/page_visibility.rs
kernel/src/sev/hv_doorbell.rs

There are multiple uses of types behind a `SharedBox`, which have the particularity that reside on hypervisor-shared memory, which means that:
1. The contents may be updated at any time by the hypervisor without synchronization.
2. The contents may contain arbitrary data, including invalid type representations.
The first use case is the `HvDoorbell` page. Since this type is `Sync` (cannot suffer from data races) and `FromBytes` (has no invalid representations), it should be accessible from behind a `SharedBox` transparently. Thus, allow for types following these characteristics to be accessed through a `SharedBox` via `Deref` or `AsRef`.
The second case is the Hyper-V hypercall pages. In this case, keep the semantic information of memory being shared by not leaking the backing pages, and …

mm/page_visibility, hyperv: multiple safety & ergonomic improvements

---

kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/mod.rs
kernel/src/cpu/idt/stage2.rs
kernel/src/cpu/idt/svsm.rs
kernel/src/cpu/smp.rs
kernel/src/cpu/vmsa.rs
kernel/src/stage2.rs
kernel/src/svsm.rs

Split the IDT into an early-boot IDT (only large enough to contain exception vectors), which is allocated on the stack, and a global IDT (with full contents), which is allocated from persistent memory.  This makes it much easier to make the IDT read-only after it has been populated.

cpu: eliminate static IDT allocation

---

kernel/src/cpu/cpuid.rs
kernel/src/utils/immut_after_init.rs

Because `ImmutAfterInitCell` can be initialized by value as well as by reference, it is suitable for holding a global static reference. Therefore, `ImmutAfterInitRef` no longer adds any unique value, and the code can be cleaned up by removing it.

utils: remove `ImmutAfterInitRef`

---

kernel/src/syscall/class0.rs
kernel/src/task/schedule.rs
kernel/src/task/tasks.rs

In commit 051e2844 ("kernel/syscall: Implement two testing syscalls") we marked `current_task_terminated()` unsafe because it can panic, but this should not be related to memory safety.

kernel/task: make `current_task_terminated()` safe

---

kernel/src/fs/init.rs

`slice::from_raw_parts` missed the safety comment.

kernel/fs: add safety comment

---

Makefile
scripts/unsafe_blocks_report.sh

This PR adds `UNSAFE_BLOCKS` and `CLIPPY_OPTIONS` to the Makefile.
These are used by the new `unsafe_blocks_report.sh` also added by this PR to print stats about undocumented unsafe blocks in our base code.
I'll open a new PR when this is merged to use the script in the CI, since our pipeline requires to have the changes in the base branch

unsafe blocks: add options to Makefile and new script to print stats

---

virtio-drivers/src/hal/fake.rs
virtio-drivers/src/queue.rs

Add missing SAFETY comments in the virtio-drivers code.
In many cases the comments were already there, simply missing the
"SAFETY" keyword.
Closes #736

virtio-drivers: Add missing SAFETY comments

---

virtio-drivers/src/hal/fake.rs

Use correct SAFETY keyword for documenting safety for Hal trait
implementation on the FakeHal struct.
Closes #736

virtio-drivers: Fix SAFETY comment for fake Hal struct

---

kernel/src/debug/gdbstub.rs
kernel/src/mm/alloc.rs
kernel/src/mm/guestmem.rs
kernel/src/mm/page_visibility.rs
kernel/src/mm/pagebox.rs
kernel/src/mm/pagetable.rs
kernel/src/mm/ptguards.rs
kernel/src/mm/validate.rs
kernel/src/mm/vm/mapping/api.rs

This PR documents all not-yet documented unsafe blocks in the memory management code.

Document unsafe blocks in memory management code

---

kernel/src/cpu/ipi.rs

Fix the format of safety comments on unsafe trait implementations to satisfy clippy.

cpu/ipi: fix safety comments

---

kernel/src/svsm.rs

Commit 56c43b2 introduced the variable `HAS_TEST_IOREQUESTS`, but it was never set. This caused all the tests calling `has_test_iorequests()` to never run.
Initialize it according to the IGVM parameter.
Fixes: 56c43b2 ("testing: Split qemu_test_env into 2 booleans")

testing: initialize HAS_TEST_IOREQUESTS variable

---

Documentation/mkdocs.yml
kernel/src/fs/ramfs.rs

This PR fixes two problems:
1. The documentation on how to run the Verus verifier is not linked in the documentation.
2. An out-of-bounds `Vec` access in RamFS code.

Documentation and RamFS Fixes

---

kernel/src/mm/ro_after_init.rs

The test fails because it expects a write right after the read-only section to fail. Fix the test so that it only expects failures when writing to the actual read-only section.

Fix `test_make_ro_after_init()`

---

kernel/src/debug/gdbstub.rs
kernel/src/debug/stacktrace.rs

This fix includes comments for unsafe blocks as well as changes to improve the safety of the debugger support code.

debug: fix safety issues with debugger implementation

---

Makefile

The IGVM file produced by `make` does not have the native flag set. This means that `launch_guest [..] --nocc` will not work.
Add `native` option to qemu and test-qemu

Makefile: add native flag for qemu builds

---

kernel/src/mm/pagetable.rs

Make clear that `make_{shared, private}_address()` strip the opposite bits first. Also, simplify `is_shared()` as the confidentiality bits are always stripped in `make_shared_address()`.

kernel/mm/pagetable: Rework C/shared bit handling

---

kernel/src/cpu/apic.rs

SVSM has been checking bits of trigger mode and assert in ICR message for IPI, however the Hardware ignores those bits and this is how Linux has been doing it since forever.
Fix handle_icr_write() to ignore those bits just like real hardware does.

cpu/apic: Fix handle_icr_write

---

Documentation/docs/installation/INSTALL.md

Document that newer versions of the IGVM library require cargo-c to build its C bindings.
Fixes: #790

Documentation: Fix build instructions for IGVM library

---

Documentation/docs/installation/INSTALL.md

The new IGVM default system-wide install target now requires su access to the rust toolchain, which is uncommon. Update our installation instructions to build and use IGVM in a local directory.

Update IGVM build and usage in INSTALL.md

---

kernel/src/virtio/hal.rs
virtio-drivers/src/hal.rs

Replace `alinged` with `aligned`, `writeble` with `writable`, and `readale` with `readable`.

virtio: fix typo in safety comments

---

Documentation/docs/installation/INSTALL.md
scripts/launch_guest.sh

With newer QEMU version(10.1), the upstream IGVM patches fail during VGA initialization. Add `-vga none `in the docs and launch script to disable VGA init until the upstream issue is resolved.
Related qemu PR is [here](https://github.com/coconut-svsm/qemu/pull/25).
cc @osteffenrh

qemu: add -vga none for guest launch

---

Cargo.lock

`cargo audit` reports a security advisor about our `slab` version:
Crate:     slab
Version:   0.4.10
Title:     Out-of-bounds access in `get_disjoint_mut` due to incorrect bounds check
Date:      2025-08-12
ID:        RUSTSEC-2025-0047
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0047
Solution:  Upgrade to >=0.4.11
Dependency tree:
slab 0.4.10
├── tokio 1.46.1
│   ├── tower 0.5.2
│   │   ├── tower-http 0.6.6
│   │   │   └── reqwest 0.12.22
│   │   │       └── aproxy 0.1.0
│   │   └── reqwest 0.12.22
│   ├── reqwest 0.12.22
│   ├── hyper-util 0.1.15
│   │   └── reqwest 0.12.22
│   └── hyper 1.6.0
│       ├── reqwest 0.12.22
│       └── hyper-util 0.1.15
└── futures-util 0.3.31
├── tower-http 0.6.6
├── tower 0.5.2
├── reqwest 0.12.22
├── hyper-util 0.1.15
└── hyper 1.6.0

Update slab to 0.4.11

---

scripts/show-stack-sizes.sh

Commit 56c0aae6 ("build: do not hardcode host target triple") added a new section in the .cargo/config.toml file, moving rustflags from the generic `[build]` section to a target-specific section `[target.x86_64-unknown-none]`.
Update the show-stack-sizes.sh script to use correct target-specific path.

scripts/show-stack-sizes: fix RUSTFLAGS variable

---

kernel/src/task/tasks.rs

Commit fd2152881e8c ("task: encapsulate thread start information for safety") modified the parameters for `start_kernel_task`. Two calls were not updated accordingly, breaking `test-in-svsm`.
Update them using `KernelThreadStartInfo`.

kernel/task: fix `start_kernel_task` parameters

---

kernel/src/platform/mod.rs
kernel/src/platform/native.rs
kernel/src/platform/snp.rs
kernel/src/platform/tdp.rs
kernel/src/virtio/hal.rs

Currently native platform does not support mmio operations. This can be useful when developing or testing drivers that rely on MMIO, like virtio-vsock or virtio-block.
Tested on top of my RFC #766 that introduces Vsock support, using `make test-in-svsm`

kernel/platform: Add mmio support for native platform

---

Cargo.toml

Top `show-stack-sizes.sh` offenders w/o the patch:
```
2280     svsm_start
2456     elf::header::Elf64Hdr::read::he4dbcb190d9ed396
2808     svsm::task::tasks::Task::create_common::h31236b6c8b389867
2936     svsm::task::exec::exec_user::h5af32c9bdff9eb44
4120     _$LT$svsm..mm..pagetable..PageTable$u20$as$u20$core..default..Default$GT$::default::hb5dd5f3760627e37
4120     _$LT$svsm..mm..pagetable..RawPageTablePart$u20$as$u20$core..default..Default$GT$::default::h800ec5e5885f3e4e
4136     svsm::sev::secrets_page::SecretsPage::copy_from::ha0efc555d365a5cb
4152     _$LT$svsm..mm..pagetable..PTPage$u20$as$u20$core..default..Default$GT$::default::hdbf3038e4b41f1cb
4152     svsm::sev::secrets_page::SecretsPage::copy_to::he32b9fc4979e69d1
4168 …
```

Increase opt-level to 1 for profile.dev
