src/mm/alloc.rs

Fix a subtle bug in allocate_zeroed_page() where inline assembly setting a memory region to zero would get optimized out due to the target address being set as an "in" parameter instead of "inout". This would cause the compiler to assume that the contents of the pointer were not changed, resulting in a crash during boot in release builds release builds. This is similar to the bug fixed in 35b8a31aa2b96e86 ("SVSM/mm/guestmem: Fix GuestPtr::read() operations").
Fix this by using zero_mem_region(), which casts the address to a raw pointer before zeroing out the region, ensuring the operation does not get opimized away.

mm/alloc: fix optimized out inline assembly

---

src/fw_cfg.rs
src/kernel_launch.rs
src/mm/pagetable.rs
src/svsm.rs

fix potential loader memory corruption

---

src/acpi/tables.rs
src/console.rs
src/cpu/extable.rs
src/cpu/idt.rs
src/cpu/percpu.rs
src/cpu/smp.rs
src/debug/stacktrace.rs
src/fw_cfg.rs
src/fw_meta.rs
src/locking/spinlock.rs
src/mm/virtualrange.rs
src/utils/bitmap_allocator.rs

Fix several trivial clippy warnings. Each commit message contains the warning that was fixed.

Fix more clippy warnings

---

src/cpu/percpu.rs
src/mm/virtualrange.rs

Apply some cargo fmt changes that managed to slip in.

Apply rustfmt changes

---

src/fs/fs.rs
src/fs/init.rs

Remove needless allocations in a couple of places, plus a refactor of the archive unpacking code.

fs: avoid needless allocations

---

Cargo.lock
Cargo.toml

Take advantage of conditional compilation, remove unused dependencies and update the rest of them.

Improve build and update dependencies

---

CONTRIBUTING.md
README.md

Mention the development mailing list in the README.md and CONTRIBUTING.md documents.

docs: mention development mailing list

---

src/acpi/tables.rs

Fix an undefined behavior that would occur when the alignment requirements for `core::slice::from_raw_parts()` would not be held. The pointer passed to this function must be aligned so that each member of the slice is itself aligned, which could not be guaranteed.
Instead of creating a new slice of u32's, iterate over the individual bytes in chunks of 4 and parse each u32 individually.
Fixes: #115
Fixes: 62f5c6fe "acpi: return ACPITable content as byte slice instead of raw pointer"

acpi/tables: fix undefined behavior due to pointer misalignment

---

src/console.rs
src/cpu/gdt.rs
src/fs/api.rs
src/fs/filesystem.rs
src/fs/ramfs.rs
src/io.rs
src/locking/spinlock.rs
src/mm/alloc.rs
src/mm/pagetable.rs
src/mm/validate.rs
src/serial.rs
src/sev/ghcb.rs
src/stage2.rs
src/svsm.rs

This pr contains the undisputed changes from #109 rebased onto the latest main branch. I'll leave #109 open for now to continue the discussion on the remaining changes.

miscellaneous fixes

---

src/mm/alloc.rs

The `SvsmAllocator` manages a list of slabs of different sizes. Since these sizes of powers of 2, we can exploit this fact to find the adequate slab for a given allocation size:
* First, round the allocation size to the next power of 2 to find the required slab size.
* Next, count the number of trailing zeros, substract the trailing zeros of the smallest slab size, and use that as an index into an array of slabs.
For example, 128 has 7 trailing zeros, which is 2 more than the smallest slab size (32). Thus, the 128-byte slab is at index 2.
This simplifies the logic, removing several conditional branches.

mm/alloc: simplify `SvsmAllocator::get_slab()` logic

---

src/utils/bitmap_allocator.rs

Cleanups of bitmap code which should bring minor performance improvements.

utils/bitmap_allocator: minor cleanups

---

src/fs/api.rs
src/fs/filesystem.rs
src/fs/init.rs
src/fs/ramfs.rs

This is related to issue #74 Document COCONUT-SVSM.

Document filesystem support. 

---

src/debug/gdbstub.rs

Implement From<usize> for ExceptionType

---

CONTRIBUTING.md
README.md

Fix links after file rename in https://github.com/coconut-svsm/svsm/pull/156

docs: Fix guidelines links

---

src/config.rs
src/lib.rs
src/mm/memory.rs
src/stage2.rs
src/svsm.rs
src/svsm_paging.rs

Defines a new structure that encapsulates launch configuration into a configuration object and controls the behavior of the launch based on the encapsulated configuration

Control startup behavior based on launch configuration

---

scripts/check-signed-off.sh
scripts/container/build.sh
scripts/container/opensuse-rust.docker
scripts/install-hooks.sh
scripts/pre-commit
scripts/test-in-svsm.sh

Add missing license headers to files under the scripts/ path.

scripts: add license headers

---

igvmbld/igvmbld.c

The checksum field in the fixed header should be calculated from the fixed and variable headers in the generated file. This is currently just set to 0. The rust IGVM library validates the checksum field when reading the file so files generated with the current version of the builder cannot be loaded when using the rust library.
This PR implements the checksum calculation in the IGVM file builder.

Populate the Checksum field in IGVM_FIXED_HEADER in the IGVM file builder

---

src/cpu/gdt.rs

In release builds the compiler did not recognize that the assembly between set_tss_entry() and clear_tss_entry() did actually consume the data written by set_tss_entry(). This make the compiler optimize away the set_tss_entry() call entirely in release builds, making the SVSM fail to boot.
Use volatile writes to update the GDT for TSS entries to force the compiler not to optimize the writes away.

SVSM/cpu/gdt: Fix boot issue around TSS loading in release builds

---

kernel/src/task/schedule.rs
kernel/src/task/tasks.rs
kernel/src/task/waiting.rs

Removed some unnecessary unwraps, improved the documentation in several places, a minor performance improvement when getting the next task and other cleanups.

task: multiple minor improvements

---

kernel/src/mm/alloc.rs
kernel/src/mm/memory.rs

Document memory management of (de)allocation operations and its related testing functions, and memory regions handling. This is related to issue #74 Document COCONUT-SVSM.

docs: Document management of allocation operations and memory regions

---

kernel/src/error.rs

Document the `SvsmError` type and its containing module.

error: document `SvsmError`

---

kernel/src/platform/snp.rs
kernel/src/sev/hv_doorbell.rs

The #HV doorbell protocol defines a "lazy" EOI model that permits a VM to indicate an intention to perform an EOI without requiring an immediate exit to the host.  This change modifies the SNP EOI flow to take advantage of lazy EOI when possible.

platform/snp: Perform lazy #HV doorbell EOI when able

---

kernel/src/task/schedule.rs

Fix module-level documentation so that it shows up in the generated docs. Fix broken links to identifiers as well.

task/schedule: fix module-level documentation

---

igvmbuilder/src/igvm_builder.rs
kernel/src/cpu/apic.rs
kernel/src/cpu/percpu.rs
kernel/src/protocols/apic.rs

This change addresses review feedback that was posted on the APIC emulation PR after it merged.

cpu/apic: Clean up APIC emulation code

---

kernel/src/cpu/idt/common.rs
kernel/src/cpu/idt/entry.S
kernel/src/debug/stacktrace.rs
kernel/src/svsm.lds
kernel/src/utils/memory_region.rs

Fix three issues in the stack unwinder to get relieable stack traces again.

Unwinder fixes

---

scripts/pre-commit

scripts/pre-commit: exclude deleted files from rustfmt check
Also exclude deleted files from header style check

scripts/pre-commit: exclude deleted files from rustfmt check

---

kernel/src/task/tasks.rs

The scheduler assumes that every new task initially executes with interrupts disabled.  Thus, every new task needs to have its initial stack frame created with interrupts disabled.  In addition, the initial state of every new task should be consistent and not related to the current flags disposition at the time the task is created, so the initial task creation should use a constant flags value instead of the current flags.

task: create new tasks with interrupts disabled

---

kernel/src/cpu/idt/svsm.rs
kernel/src/fs/filesystem.rs
kernel/src/svsm.rs
kernel/src/syscall/class0.rs
kernel/src/syscall/class1.rs
kernel/src/task/exec.rs
kernel/src/task/schedule.rs
kernel/src/task/tasks.rs
syscall/src/class0.rs
syscall/src/def.rs

This is 6th PR in the userspace series. This PR implements support for EXEC syscalls.

Userspace support: Implement exec syscall support

---

kernel/src/task/tasks.rs

On some platforms the SVSM is not ready to run with IRQs enabled. This also includes user-mode tasks, so check whether the platform supports receiving IRQs before enabling IRQs in user-mode.

kernel/task: Do not unconditionally enable IRQ in user-mode

---

kernel/src/cpu/ipi.rs

When sending an IPI to all CPUs or all-but-self, it may be the case that the global CPU array is tracking CPUs that are not yet online.  These CPUs should be ignored when sending IPIs because they are not able to respond to IPI requests.

cpu/ipi: do not target offline CPUs

---

kernel/src/cpu/ipi.rs

Atomic values are `Sync` and therefore are candidates for inclusion in multicast IPI messages.  However, unless the value is copied back from the shared buffer, it will not be visible to the sender.  Therefore, the `IpiMessage` trait must expose a method that permits finalization of the message send by copying back any atomic fields.

cpu/ipi: permit multicast IPI messages to hold atomic values

---

libtcgtpm/deps/libcrt/Makefile
libtcgtpm/deps/libcrt/include/libcrt.h
libtcgtpm/deps/libcrt/src/stdlib/qsort.c
libtcgtpm/deps/libcrt/src/string/memchr.c
libtcgtpm/deps/libcrt/src/string/stpcpy.c
libtcgtpm/deps/libcrt/src/string/stpncpy.c
libtcgtpm/deps/libcrt/src/string/strchrnul.c
libtcgtpm/deps/libcrt/src/string/strlen.c
libtcgtpm/deps/libcrt/src/stub.c

Fix some compiler warnings and trun on -Wall -Werror for libcrt.

libcrt improvements

---

libtcgtpm/Makefile
libtcgtpm/deps/libcrt/include/libcrt.h

TCG TPM reference implementation recently merged 2 patches for OpenSSL 3.5 support and adds support in ./configure for disabling pthreads, removing the need for our workaround.

libtcgtpm: bump TPM reference implementation to latest upstream and OpenSSL to 3.5

---

kernel/src/svsm.rs
kernel/src/syscall/class0.rs
kernel/src/task/exec.rs
scripts/test-qemu-nocc-boot.sh

Several clean-up commits cherry-picked from https://github.com/coconut-svsm/svsm/pull/547

kernel: miscellaneous cleanups

---

igvmbuilder/src/ovmf_firmware.rs

Rework the OVMF parser in `igvmbuilder`. Take advantage of Rust slice's properties and the `zerocopy` crate and reduce code redundancy.

igvmbuilder/ovmf: Rework using slices and zerocopy

---

kernel/src/sev/secrets_page.rs

Change various copy operations on the secrets page to use pointers directly instead of using copy operations.  This ensures that a non-optimizing compiler will not blow up the stack by creating page-sized stack locals for the sake of copying data.

sev/secrets_page: clean up stack usage
